// Branch data configuration for mock data generation
const branchConfig = {
  'RDA SUMEDANG': {
    region: 'JAWA BARAT',
    coordinates: {
      center: {
        lat: -6.8575162,
        lng: 107.9240116,
      },
      radius: 55,
    },
    vehicles: ['B9144SCN', 'B99871SCM', 'B9123SCN', 'B9456SCM', 'B9789SCN', 'B9234SCM', 'B9567SCN'],
    drivers: [
      { name: 'SOEBANGKIT', helper: 'DENINURJAMAN' },
      { name: 'ROHMAT', helper: 'DEDE' },
      { name: 'ASEP', helper: 'UJANG' },
      { name: 'DADANG', helper: 'CECEP' },
      { name: 'AGUS', helper: 'DEDI' },
      { name: 'YAYAN', helper: 'ASEP' },
      { name: 'UJANG', helper: 'CECEP' },
    ],
    customers: [
      // Local stores/warung (40% = ~44 customers)
      { name: 'HIDAYAT', location: 'JL PRABU GEUSAN ULUN NO.12', deliveryCycle: 'monthly' },
      { name: 'YANTO 2', location: 'JL MAYOR ABDURAHMAN NO.45', deliveryCycle: 'monthly' },
      { name: 'SELVIE', location: 'JL TANJUNGSARI NO.78', deliveryCycle: 'biweekly' },
      { name: 'MICRO MART', location: 'JL RANCAKALONG NO.23', deliveryCycle: 'biweekly' },
      { name: 'AL BAROKAH', location: 'JL SITURAJA NO.56', deliveryCycle: 'weekly' },
      { name: 'ADE SUMBER REZEKI', location: 'JL DARMARAJA NO.34', deliveryCycle: 'weekly' },
      { name: 'WARUNG BERKAH', location: 'JL CONGGEANG NO.67', deliveryCycle: 'monthly' },
      { name: 'TOKO MAKMUR', location: 'JL BUAHDUA NO.89', deliveryCycle: 'weekly' },
      { name: 'WARUNG SEJAHTERA', location: 'JL CISITU NO.12', deliveryCycle: 'biweekly' },
      { name: 'TOKO REZEKI', location: 'JL JATIGEDE NO.45', deliveryCycle: 'biweekly' },
      { name: 'WARUNG BAROKAH', location: 'JL WADO NO.78', deliveryCycle: 'weekly' },
      { name: 'TOKO SINAR JAYA', location: 'JL JATINUNGGAL NO.90', deliveryCycle: 'monthly' },
      { name: 'WARUNG MAJU', location: 'JL TOMO NO.34', deliveryCycle: 'biweekly' },
      { name: 'TOKO BERKAH JAYA', location: 'JL UJUNGJAYA NO.56', deliveryCycle: 'biweekly' },
      { name: 'WARUNG SEJATI', location: 'JL CIMALAKA NO.78', deliveryCycle: 'weekly' },
      { name: 'TOKO MAKMUR JAYA', location: 'JL PASEH NO.90', deliveryCycle: 'weekly' },
      { name: 'WARUNG ABADI', location: 'JL CIBUGEL NO.12', deliveryCycle: 'monthly' },
      { name: 'TOKO SUMBER REJEKI', location: 'JL TANJUNGKERTA NO.34', deliveryCycle: 'monthly' },
      { name: 'WARUNG BAHAGIA', location: 'JL SUKASARI NO.56', deliveryCycle: 'biweekly' },
      { name: 'TOKO JAYA ABADI', location: 'JL PAMULIHAN NO.78', deliveryCycle: 'monthly' },
      { name: 'WARUNG MAKMUR', location: 'JL TANJUNGMEDAR NO.90', deliveryCycle: 'weekly' },
      { name: 'TOKO BERKAH ABADI', location: 'JL SURIAN NO.12', deliveryCycle: 'weekly' },
      { name: 'WARUNG SEJAHTERA', location: 'JL GANEAS NO.34', deliveryCycle: 'weekly' },
      { name: 'TOKO MAJU JAYA', location: 'JL SITURAJA UTARA NO.56', deliveryCycle: 'monthly' },
      { name: 'WARUNG BAROKAH', location: 'JL CISARUA NO.78', deliveryCycle: 'biweekly' },
      { name: 'TOKO SINAR ABADI', location: 'JL JATINGALIH NO.90', deliveryCycle: 'biweekly' },
      { name: 'WARUNG BERKAH', location: 'JL WADO NO.12', deliveryCycle: 'monthly' },
      { name: 'TOKO MAKMUR SEJATI', location: 'JL DARMARAJA NO.34', deliveryCycle: 'monthly' },
      { name: 'WARUNG JAYA MAKMUR', location: 'JL CIBUGEL NO.56', deliveryCycle: 'biweekly' },
      { name: 'TOKO ABADI JAYA', location: 'JL BUAHDUA NO.78', deliveryCycle: 'monthly' },
      { name: 'WARUNG SUMBER REJEKI', location: 'JL JATIGEDE NO.90', deliveryCycle: 'weekly' },
      { name: 'TOKO BERKAH UTAMA', location: 'JL TOMO NO.12', deliveryCycle: 'monthly' },
      { name: 'WARUNG MAKMUR JAYA', location: 'JL UJUNGJAYA NO.34', deliveryCycle: 'monthly' },
      { name: 'TOKO SEJAHTERA', location: 'JL CONGGEANG NO.56', deliveryCycle: 'weekly' },
      { name: 'WARUNG BAROKAH', location: 'JL PASEH NO.78', deliveryCycle: 'biweekly' },
      { name: 'TOKO MAJU BERKAH', location: 'JL CIMALAKA NO.90', deliveryCycle: 'biweekly' },
      { name: 'WARUNG ABADI JAYA', location: 'JL TANJUNGKERTA NO.12', deliveryCycle: 'monthly' },
      { name: 'TOKO SINAR MAKMUR', location: 'JL SUKASARI NO.34', deliveryCycle: 'biweekly' },
      { name: 'WARUNG JAYA ABADI', location: 'JL PAMULIHAN NO.56', deliveryCycle: 'monthly' },
      { name: 'TOKO BERKAH MAKMUR', location: 'JL TANJUNGMEDAR NO.78', deliveryCycle: 'biweekly' },
      { name: 'WARUNG SEJAHTERA', location: 'JL SURIAN NO.90', deliveryCycle: 'biweekly' },
      { name: 'TOKO MAJU SEJATI', location: 'JL GANEAS NO.12', deliveryCycle: 'monthly' },
      { name: 'WARUNG BAROKAH', location: 'JL SITURAJA UTARA NO.34', deliveryCycle: 'monthly' },
      { name: 'TOKO ABADI MAKMUR', location: 'JL CISARUA NO.56', deliveryCycle: 'monthly' },

      // Chain stores (20% = ~22 customers)
      {
        name: 'INDOMARET SUMEDANG 1',
        location: 'JL PRABU GEUSAN ULUN NO.123',
        deliveryCycle: 'biweekly',
      },
      {
        name: 'INDOMARET SUMEDANG 2',
        location: 'JL MAYOR ABDURAHMAN NO.45',
        deliveryCycle: 'monthly',
      },
      { name: 'INDOMARET SUMEDANG 3', location: 'JL TANJUNGSARI NO.67', deliveryCycle: 'biweekly' },
      { name: 'INDOMARET SUMEDANG 4', location: 'JL RANCAKALONG NO.89', deliveryCycle: 'monthly' },
      { name: 'INDOMARET SUMEDANG 5', location: 'JL SITURAJA NO.12', deliveryCycle: 'weekly' },
      { name: 'INDOMARET SUMEDANG 6', location: 'JL DARMARAJA NO.34', deliveryCycle: 'biweekly' },
      {
        name: 'ALFAMART SUMEDANG 1',
        location: 'JL PRABU GEUSAN ULUN NO.89',
        deliveryCycle: 'biweekly',
      },
      {
        name: 'ALFAMART SUMEDANG 2',
        location: 'JL MAYOR ABDURAHMAN NO.12',
        deliveryCycle: 'monthly',
      },
      { name: 'ALFAMART SUMEDANG 3', location: 'JL TANJUNGSARI NO.34', deliveryCycle: 'weekly' },
      { name: 'ALFAMART SUMEDANG 4', location: 'JL RANCAKALONG NO.56', deliveryCycle: 'biweekly' },
      { name: 'ALFAMART SUMEDANG 5', location: 'JL SITURAJA NO.78', deliveryCycle: 'monthly' },
      { name: 'ALFAMART SUMEDANG 6', location: 'JL DARMARAJA NO.90', deliveryCycle: 'monthly' },
      {
        name: 'YOMART SUMEDANG 1',
        location: 'JL PRABU GEUSAN ULUN NO.12',
        deliveryCycle: 'monthly',
      },
      {
        name: 'YOMART SUMEDANG 2',
        location: 'JL MAYOR ABDURAHMAN NO.34',
        deliveryCycle: 'monthly',
      },
      { name: 'YOMART SUMEDANG 3', location: 'JL TANJUNGSARI NO.56', deliveryCycle: 'monthly' },
      { name: 'YOMART SUMEDANG 4', location: 'JL RANCAKALONG NO.78', deliveryCycle: 'weekly' },
      { name: 'YOMART SUMEDANG 5', location: 'JL SITURAJA NO.90', deliveryCycle: 'weekly' },
      { name: 'YOMART SUMEDANG 6', location: 'JL DARMARAJA NO.12', deliveryCycle: 'biweekly' },
      {
        name: 'LAWSON SUMEDANG 1',
        location: 'JL PRABU GEUSAN ULUN NO.34',
        deliveryCycle: 'biweekly',
      },
      {
        name: 'LAWSON SUMEDANG 2',
        location: 'JL MAYOR ABDURAHMAN NO.56',
        deliveryCycle: 'monthly',
      },
      { name: 'LAWSON SUMEDANG 3', location: 'JL TANJUNGSARI NO.78', deliveryCycle: 'weekly' },
      { name: 'LAWSON SUMEDANG 4', location: 'JL RANCAKALONG NO.90', deliveryCycle: 'weekly' },

      // Mini markets (30% = ~33 customers)
      { name: 'MINI MARKET CENTRAL', location: 'JL ANGKREK NO.56', deliveryCycle: 'monthly' },
      { name: 'FAMILY MART', location: 'JL PASAR WAGE NO.78', deliveryCycle: 'biweekly' },
      { name: 'FRESH MART', location: 'JL TANJUNGSARI NO.90', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET ABADI', location: 'JL SUMEDANG UTARA NO.123', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET SEJAHTERA', location: 'JL PASEH NO.45', deliveryCycle: 'biweekly' },
      { name: 'MINI MARKET BERKAH', location: 'JL CONGGEANG NO.67', deliveryCycle: 'biweekly' },
      { name: 'MINI MARKET JAYA', location: 'JL BUAHDUA NO.89', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET MAKMUR', location: 'JL CISITU NO.12', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET SENTOSA', location: 'JL JATIGEDE NO.34', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET BAROKAH', location: 'JL WADO NO.56', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET ABADI', location: 'JL JATINUNGGAL NO.78', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET SEJATI', location: 'JL TOMO NO.90', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET MAJU', location: 'JL UJUNGJAYA NO.12', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET JAYA', location: 'JL CIMALAKA NO.34', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET BERKAH', location: 'JL PASEH NO.56', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET MAKMUR', location: 'JL TANJUNGKERTA NO.78', deliveryCycle: 'biweekly' },
      { name: 'MINI MARKET SENTOSA', location: 'JL SUKASARI NO.90', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET BAROKAH', location: 'JL PAMULIHAN NO.12', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET ABADI', location: 'JL TANJUNGMEDAR NO.34', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET SEJATI', location: 'JL SURIAN NO.56', deliveryCycle: 'biweekly' },
      { name: 'MINI MARKET MAJU', location: 'JL GANEAS NO.78', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET JAYA', location: 'JL SITURAJA UTARA NO.90', deliveryCycle: 'biweekly' },
      { name: 'MINI MARKET BERKAH', location: 'JL CISARUA NO.12', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET MAKMUR', location: 'JL JATINGALIH NO.34', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET SENTOSA', location: 'JL WADO NO.56', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET BAROKAH', location: 'JL DARMARAJA NO.78', deliveryCycle: 'biweekly' },
      { name: 'MINI MARKET ABADI', location: 'JL CIBUGEL NO.90', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET SEJATI', location: 'JL BUAHDUA NO.12', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET MAJU', location: 'JL JATIGEDE NO.34', deliveryCycle: 'biweekly' },
      { name: 'MINI MARKET JAYA', location: 'JL TOMO NO.56', deliveryCycle: 'biweekly' },
      { name: 'MINI MARKET BERKAH', location: 'JL UJUNGJAYA NO.78', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET MAKMUR', location: 'JL CONGGEANG NO.90', deliveryCycle: 'weekly' },

      // Grosir/wholesale (10% = ~11 customers)
      { name: 'GROSIR MAKMUR JAYA', location: 'JL RAYA SUMEDANG NO.100', deliveryCycle: 'weekly' },
      { name: 'GROSIR SEJAHTERA', location: 'JL PASAR INPRES NO.200', deliveryCycle: 'weekly' },
      { name: 'GROSIR BAROKAH', location: 'JL KEBON KOPI NO.150', deliveryCycle: 'weekly' },
      {
        name: 'GROSIR MAJU BERSAMA',
        location: 'JL PRABU GEUSAN ULUN NO.300',
        deliveryCycle: 'monthly',
      },
      { name: 'GROSIR ABADI', location: 'JL MAYOR ABDURAHMAN NO.250', deliveryCycle: 'biweekly' },
      { name: 'GROSIR BERKAH', location: 'JL TANJUNGSARI NO.350', deliveryCycle: 'weekly' },
      { name: 'GROSIR JAYA', location: 'JL RANCAKALONG NO.400', deliveryCycle: 'biweekly' },
      { name: 'GROSIR MAKMUR', location: 'JL SITURAJA NO.450', deliveryCycle: 'monthly' },
      { name: 'GROSIR SEJATI', location: 'JL DARMARAJA NO.500', deliveryCycle: 'biweekly' },
      { name: 'GROSIR SENTOSA', location: 'JL CONGGEANG NO.550', deliveryCycle: 'weekly' },
      { name: 'GROSIR UTAMA', location: 'JL BUAHDUA NO.600', deliveryCycle: 'weekly' },
    ],
  },
  'RDA MANADO': {
    region: 'SULAWESI',
    coordinates: {
      center: {
        lat: 1.4468417,
        lng: 125.17706,
      },
      radius: 50,
    },
    vehicles: ['DB8432FJ', 'DB8809FJ', 'DB8567FJ', 'DB8234FJ', 'DB8890FJ'],
    drivers: [
      { name: 'MELKY', helper: 'AHMAD' },
      { name: 'MELDY', helper: 'KRISTIN' },
      { name: 'ANDI', helper: 'YUSUF' },
      { name: 'RAHMAN', helper: 'DEDI' },
      { name: 'BAMBANG', helper: 'AGUS' },
    ],
    customers: [
      // Local stores/warung (40% = ~44 customers)
      { name: 'USAHA MANDIRI', location: 'JL BITUNG NO.12', deliveryCycle: 'monthly' },
      { name: 'MADURA MART', location: 'JL BITUNG NO.34', deliveryCycle: 'weekly' },
      { name: 'TOKO NONA CINDY', location: 'JL KEMA NO.56', deliveryCycle: 'monthly' },
      { name: 'BINA KARYA SANANA', location: 'JL PELABUHAN NO.78', deliveryCycle: 'biweekly' },
      { name: 'WARUNG BERKAH', location: 'JL WALANDA MARAMIS NO.90', deliveryCycle: 'monthly' },
      { name: 'TOKO SEJAHTERA', location: 'JL BABE PALAR NO.12', deliveryCycle: 'weekly' },
      { name: 'WARUNG MAKMUR', location: 'JL LUMIMUUT NO.34', deliveryCycle: 'weekly' },
      { name: 'TOKO BAROKAH', location: 'JL TOAR NO.56', deliveryCycle: 'monthly' },
      { name: 'WARUNG REZEKI', location: 'JL WAKEKE NO.78', deliveryCycle: 'monthly' },
      { name: 'TOKO JAYA', location: 'JL SARAPUNG NO.90', deliveryCycle: 'biweekly' },
      { name: 'WARUNG ABADI', location: 'JL GARUDA NO.12', deliveryCycle: 'monthly' },
      { name: 'TOKO SINAR JAYA', location: 'JL TIKALA NO.34', deliveryCycle: 'weekly' },
      { name: 'WARUNG BERKAH', location: 'JL TUMINTING NO.56', deliveryCycle: 'monthly' },
      { name: 'TOKO SEJAHTERA', location: 'JL WANEA NO.78', deliveryCycle: 'biweekly' },
      { name: 'WARUNG MAJU MAKMUR', location: 'JL MALALAYANG NO.90', deliveryCycle: 'monthly' },
      { name: 'TOKO JAYA ABADI', location: 'JL MAPANGET NO.12', deliveryCycle: 'monthly' },
      { name: 'WARUNG BERKAH ABADI', location: 'JL TONGKAINA NO.34', deliveryCycle: 'biweekly' },
      { name: 'TOKO BERKAH UTAMA', location: 'JL TELING NO.56', deliveryCycle: 'weekly' },
      { name: 'WARUNG JAYA MAKMUR', location: 'JL SARIO NO.78', deliveryCycle: 'weekly' },
      { name: 'TOKO SEJAHTERA ABADI', location: 'JL RANOTANA NO.90', deliveryCycle: 'monthly' },
      {
        name: 'WARUNG SINAR SEJAHTERA',
        location: 'JL TIKALA ARES NO.12',
        deliveryCycle: 'biweekly',
      },
      { name: 'TOKO MAKMUR JAYA', location: 'JL PAAL DUA NO.34', deliveryCycle: 'monthly' },
      { name: 'WARUNG SUKSES JAYA', location: 'JL BETHESDA NO.56', deliveryCycle: 'monthly' },
      { name: 'TOKO ABADI MAKMUR', location: 'JL KAMPUNG ISLAM NO.78', deliveryCycle: 'weekly' },
      { name: 'WARUNG JAYA MANDIRI', location: 'JL SANTIAGO NO.90', deliveryCycle: 'weekly' },
      { name: 'TOKO SINAR HARAPAN', location: 'JL BAHU NO.12', deliveryCycle: 'biweekly' },
      { name: 'WARUNG BERKAH JAYA', location: 'JL KLEAK NO.34', deliveryCycle: 'monthly' },
      { name: 'TOKO MAKMUR SEJAHTERA', location: 'JL MALENDENG NO.56', deliveryCycle: 'monthly' },
      { name: 'WARUNG ABADI SENTOSA', location: 'JL KOMBOS NO.78', deliveryCycle: 'monthly' },
      { name: 'TOKO SINAR TERANG', location: 'JL KAIRAGI NO.90', deliveryCycle: 'biweekly' },
      { name: 'WARUNG MAJU JAYA', location: 'JL PANIKI NO.12', deliveryCycle: 'weekly' },
      { name: 'TOKO BERKAH ABADI', location: 'JL MAUMBI NO.34', deliveryCycle: 'weekly' },
      { name: 'WARUNG SEJAHTERA', location: 'JL AIRMADIDI NO.56', deliveryCycle: 'weekly' },
      { name: 'TOKO MAKMUR JAYA', location: 'JL KAUDITAN NO.78', deliveryCycle: 'biweekly' },
      { name: 'WARUNG BAROKAH', location: 'JL TONDANO NO.90', deliveryCycle: 'monthly' },
      { name: 'TOKO SINAR ABADI', location: 'JL TOMOHON NO.12', deliveryCycle: 'biweekly' },
      { name: 'WARUNG BERKAH', location: 'JL KAWANGKOAN NO.34', deliveryCycle: 'biweekly' },
      { name: 'TOKO MAKMUR SEJATI', location: 'JL LANGOWAN NO.56', deliveryCycle: 'weekly' },
      { name: 'WARUNG JAYA MAKMUR', location: 'JL RATAHAN NO.78', deliveryCycle: 'biweekly' },
      { name: 'TOKO ABADI JAYA', location: 'JL BELANG NO.90', deliveryCycle: 'biweekly' },
      { name: 'WARUNG SUMBER REJEKI', location: 'JL AMURANG NO.12', deliveryCycle: 'biweekly' },
      { name: 'TOKO BERKAH UTAMA', location: 'JL TARERAN NO.34', deliveryCycle: 'weekly' },
      { name: 'WARUNG MAKMUR JAYA', location: 'JL MOTOLING NO.56', deliveryCycle: 'weekly' },

      // Chain stores (20% = ~22 customers)
      { name: 'INDOMARET MANADO 1', location: 'JL PIERE TENDEAN NO.123', deliveryCycle: 'monthly' },
      { name: 'INDOMARET MANADO 2', location: 'JL SAM RATULANGI NO.45', deliveryCycle: 'monthly' },
      { name: 'INDOMARET MANADO 3', location: 'JL SUDIRMAN NO.67', deliveryCycle: 'monthly' },
      {
        name: 'INDOMARET MANADO 4',
        location: 'JL WALANDA MARAMIS NO.89',
        deliveryCycle: 'monthly',
      },
      { name: 'INDOMARET MANADO 5', location: 'JL MARTADINATA NO.12', deliveryCycle: 'weekly' },
      { name: 'INDOMARET MANADO 6', location: 'JL BETHESDA NO.34', deliveryCycle: 'monthly' },
      {
        name: 'ALFAMART MANADO 1',
        location: 'JL WOLTER MONGINSIDI NO.56',
        deliveryCycle: 'monthly',
      },
      { name: 'ALFAMART MANADO 2', location: 'JL BABE PALAR NO.78', deliveryCycle: 'monthly' },
      { name: 'ALFAMART MANADO 3', location: 'JL LUMIMUUT NO.90', deliveryCycle: 'monthly' },
      { name: 'ALFAMART MANADO 4', location: 'JL TOAR NO.12', deliveryCycle: 'biweekly' },
      { name: 'ALFAMART MANADO 5', location: 'JL WAKEKE NO.34', deliveryCycle: 'monthly' },
      { name: 'ALFAMART MANADO 6', location: 'JL SARAPUNG NO.56', deliveryCycle: 'biweekly' },
      { name: 'CIRCLE K MANADO 1', location: 'JL PIERE TENDEAN NO.78', deliveryCycle: 'weekly' },
      { name: 'CIRCLE K MANADO 2', location: 'JL SAM RATULANGI NO.90', deliveryCycle: 'weekly' },
      { name: 'CIRCLE K MANADO 3', location: 'JL SUDIRMAN NO.12', deliveryCycle: 'weekly' },
      { name: 'LAWSON MANADO 1', location: 'JL WALANDA MARAMIS NO.34', deliveryCycle: 'monthly' },
      { name: 'LAWSON MANADO 2', location: 'JL MARTADINATA NO.56', deliveryCycle: 'weekly' },
      { name: 'LAWSON MANADO 3', location: 'JL BETHESDA NO.78', deliveryCycle: 'weekly' },
      {
        name: 'FAMILY MART MANADO 1',
        location: 'JL WOLTER MONGINSIDI NO.90',
        deliveryCycle: 'weekly',
      },
      { name: 'FAMILY MART MANADO 2', location: 'JL BABE PALAR NO.12', deliveryCycle: 'weekly' },
      { name: 'FAMILY MART MANADO 3', location: 'JL LUMIMUUT NO.34', deliveryCycle: 'weekly' },
      { name: 'FAMILY MART MANADO 4', location: 'JL TOAR NO.56', deliveryCycle: 'biweekly' },

      // Mini markets (30% = ~33 customers)
      { name: 'MINI MARKET CENTRAL', location: 'JL TIKALA NO.78', deliveryCycle: 'weekly' },
      { name: 'FRESH MART MANADO', location: 'JL TUMINTING NO.90', deliveryCycle: 'biweekly' },
      { name: 'MULTI MART', location: 'JL SINGKIL NO.12', deliveryCycle: 'weekly' },
      { name: 'SMART MART', location: 'JL WANEA NO.34', deliveryCycle: 'monthly' },
      { name: 'MEGA MART', location: 'JL WENANG NO.56', deliveryCycle: 'biweekly' },
      { name: 'STAR MART', location: 'JL MALALAYANG NO.78', deliveryCycle: 'biweekly' },
      { name: 'FAMILY MART', location: 'JL MAPANGET NO.90', deliveryCycle: 'monthly' },
      { name: 'QUICK MART', location: 'JL BUNAKEN NO.12', deliveryCycle: 'weekly' },
      { name: 'DAILY MART', location: 'JL TONGKAINA NO.34', deliveryCycle: 'biweekly' },
      { name: 'HAPPY MART', location: 'JL BAILANG NO.56', deliveryCycle: 'biweekly' },
      { name: 'MINI MARKET ABADI', location: 'JL TELING NO.78', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET SEJAHTERA', location: 'JL SARIO NO.90', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET BERKAH', location: 'JL TITIWUNGEN NO.12', deliveryCycle: 'biweekly' },
      { name: 'MINI MARKET JAYA', location: 'JL RANOTANA NO.34', deliveryCycle: 'biweekly' },
      { name: 'MINI MARKET MAKMUR', location: 'JL WINANGUN NO.56', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET SENTOSA', location: 'JL TIKALA ARES NO.78', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET BAROKAH', location: 'JL PAAL DUA NO.90', deliveryCycle: 'biweekly' },
      { name: 'MINI MARKET ABADI', location: 'JL BETHESDA NO.12', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET SEJATI', location: 'JL KAMPUNG ISLAM NO.34', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET MAJU', location: 'JL SANTIAGO NO.56', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET JAYA', location: 'JL BAHU NO.78', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET BERKAH', location: 'JL KLEAK NO.90', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET MAKMUR', location: 'JL MALENDENG NO.12', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET SENTOSA', location: 'JL KOMBOS NO.34', deliveryCycle: 'biweekly' },
      { name: 'MINI MARKET BAROKAH', location: 'JL KAIRAGI NO.56', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET ABADI', location: 'JL PANIKI NO.78', deliveryCycle: 'biweekly' },
      { name: 'MINI MARKET SEJATI', location: 'JL MAUMBI NO.90', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET MAJU', location: 'JL AIRMADIDI NO.12', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET JAYA', location: 'JL KAUDITAN NO.34', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET BERKAH', location: 'JL TONDANO NO.56', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET MAKMUR', location: 'JL TOMOHON NO.78', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET SENTOSA', location: 'JL KAWANGKOAN NO.90', deliveryCycle: 'biweekly' },
      { name: 'MINI MARKET BAROKAH', location: 'JL LANGOWAN NO.12', deliveryCycle: 'biweekly' },

      // Grosir/wholesale (10% = ~11 customers)
      {
        name: 'GROSIR MAKMUR JAYA',
        location: 'JL PIERE TENDEAN NO.100',
        deliveryCycle: 'biweekly',
      },
      { name: 'GROSIR SEJAHTERA', location: 'JL SAM RATULANGI NO.200', deliveryCycle: 'monthly' },
      { name: 'GROSIR ABADI', location: 'JL SUDIRMAN NO.150', deliveryCycle: 'monthly' },
      {
        name: 'GROSIR MAJU BERSAMA',
        location: 'JL WALANDA MARAMIS NO.300',
        deliveryCycle: 'weekly',
      },
      { name: 'GROSIR BERKAH', location: 'JL MARTADINATA NO.250', deliveryCycle: 'monthly' },
      { name: 'GROSIR JAYA', location: 'JL BETHESDA NO.350', deliveryCycle: 'monthly' },
      { name: 'GROSIR MAKMUR', location: 'JL WOLTER MONGINSIDI NO.400', deliveryCycle: 'monthly' },
      { name: 'GROSIR SEJATI', location: 'JL BABE PALAR NO.450', deliveryCycle: 'biweekly' },
      { name: 'GROSIR SENTOSA', location: 'JL LUMIMUUT NO.500', deliveryCycle: 'biweekly' },
      { name: 'GROSIR UTAMA', location: 'JL TOAR NO.550', deliveryCycle: 'weekly' },
      { name: 'GROSIR BAROKAH', location: 'JL WAKEKE NO.600', deliveryCycle: 'monthly' },
    ],
  },
  'RDA GORONTALO': {
    region: 'SULAWESI',
    coordinates: {
      center: {
        lat: 0.5585585585585585,
        lng: 123.03287331075036,
      },
      radius: 65,
    },
    vehicles: ['DG8171KB', 'DG8234KB', 'DG8567KB'],
    drivers: [
      { name: 'AYUB', helper: 'ZULKIFLI MALANGO' },
      { name: 'RAHMAN', helper: 'ANDI' },
      { name: 'YUSUF', helper: 'DEDI' },
    ],
    customers: [
      // Local stores/warung (40% = ~44 customers)
      { name: 'SALSABILA MART', location: 'JL PALMA NO.12', deliveryCycle: 'monthly' },
      { name: 'SAZKIA', location: 'JL KOMBOS TIMUR NO.34', deliveryCycle: 'weekly' },
      { name: 'MAKRO', location: 'JL KOTA SELATAN NO.56', deliveryCycle: 'weekly' },
      { name: 'IRA', location: 'JL IMAM BONJOL NO.78', deliveryCycle: 'weekly' },
      { name: 'WARUNG BERKAH', location: 'JL AHMAD YANI NO.90', deliveryCycle: 'weekly' },
      { name: 'TOKO SEJAHTERA', location: 'JL SUDIRMAN NO.12', deliveryCycle: 'weekly' },
      { name: 'WARUNG MAKMUR', location: 'JL NANI WARTABONE NO.34', deliveryCycle: 'weekly' },
      { name: 'TOKO BAROKAH', location: 'JL HB JASSIN NO.56', deliveryCycle: 'weekly' },
      { name: 'WARUNG REZEKI', location: 'JL 23 JANUARI NO.78', deliveryCycle: 'biweekly' },
      { name: 'TOKO JAYA', location: 'JL PANJAITAN NO.90', deliveryCycle: 'weekly' },
      // Add more local stores to reach ~44 total
      { name: 'WARUNG ABADI', location: 'JL AGUS SALIM NO.12', deliveryCycle: 'weekly' },
      { name: 'TOKO SINAR JAYA', location: 'JL DEWI SARTIKA NO.34', deliveryCycle: 'weekly' },
      { name: 'WARUNG BERKAH', location: 'JL ANDALAS NO.56', deliveryCycle: 'monthly' },
      { name: 'TOKO SEJAHTERA', location: 'JL BUDI UTOMO NO.78', deliveryCycle: 'weekly' },
      { name: 'WARUNG MAJU MAKMUR', location: 'JL JAKARTA NO.90', deliveryCycle: 'weekly' },
      {
        name: 'TOKO JAYA ABADI',
        location: 'JL ACHMAD NADJAMUDDIN NO.12',
        deliveryCycle: 'biweekly',
      },
      { name: 'WARUNG BERKAH ABADI', location: 'JL SAMRATULANGI NO.34', deliveryCycle: 'weekly' },
      { name: 'TOKO BERKAH UTAMA', location: 'JL SULTAN BOTUTIHE NO.56', deliveryCycle: 'monthly' },
      {
        name: 'WARUNG JAYA MAKMUR',
        location: 'JL WOLTER MONGINSIDI NO.78',
        deliveryCycle: 'weekly',
      },
      { name: 'TOKO SEJAHTERA ABADI', location: 'JL AHMAD YANI NO.90', deliveryCycle: 'weekly' },
      { name: 'WARUNG SINAR SEJAHTERA', location: 'JL PERTIWI NO.12', deliveryCycle: 'biweekly' },
      { name: 'TOKO MAKMUR JAYA', location: 'JL SAWIT NO.34', deliveryCycle: 'weekly' },
      { name: 'WARUNG SUKSES JAYA', location: 'JL RAMBUTAN NO.56', deliveryCycle: 'biweekly' },
      { name: 'TOKO ABADI MAKMUR', location: 'JL DURIAN NO.78', deliveryCycle: 'biweekly' },
      { name: 'WARUNG JAYA MANDIRI', location: 'JL MANGGA NO.90', deliveryCycle: 'biweekly' },
      { name: 'TOKO SINAR HARAPAN', location: 'JL JERUK NO.12', deliveryCycle: 'weekly' },
      { name: 'WARUNG BERKAH JAYA', location: 'JL NANAS NO.34', deliveryCycle: 'weekly' },
      { name: 'TOKO MAKMUR SEJAHTERA', location: 'JL KELAPA NO.56', deliveryCycle: 'biweekly' },
      { name: 'WARUNG ABADI SENTOSA', location: 'JL PISANG NO.78', deliveryCycle: 'weekly' },
      { name: 'TOKO SINAR TERANG', location: 'JL MANGGIS NO.90', deliveryCycle: 'monthly' },
      {
        name: 'WARUNG MAJU JAYA',
        location: 'JL SULTAN HASANUDDIN NO.12',
        deliveryCycle: 'biweekly',
      },
      { name: 'TOKO BERKAH ABADI', location: 'JL RAJAWALI NO.34', deliveryCycle: 'weekly' },
      { name: 'WARUNG SEJAHTERA', location: 'JL MERDEKA NO.56', deliveryCycle: 'monthly' },
      { name: 'TOKO MAKMUR JAYA', location: 'JL VETERAN NO.78', deliveryCycle: 'monthly' },
      { name: 'WARUNG BAROKAH', location: 'JL PAHLAWAN NO.90', deliveryCycle: 'monthly' },
      { name: 'TOKO SINAR ABADI', location: 'JL DIPONEGORO NO.12', deliveryCycle: 'weekly' },
      { name: 'WARUNG BERKAH', location: 'JL GAJAH MADA NO.34', deliveryCycle: 'monthly' },
      {
        name: 'TOKO MAKMUR SEJATI',
        location: 'JL SULTAN BOTUTIHE NO.56',
        deliveryCycle: 'monthly',
      },
      {
        name: 'WARUNG JAYA MAKMUR',
        location: 'JL WOLTER MONGINSIDI NO.78',
        deliveryCycle: 'weekly',
      },
      { name: 'TOKO ABADI JAYA', location: 'JL AHMAD YANI NO.90', deliveryCycle: 'weekly' },
      { name: 'WARUNG SUMBER REJEKI', location: 'JL PERTIWI NO.12', deliveryCycle: 'biweekly' },
      { name: 'TOKO BERKAH UTAMA', location: 'JL SAWIT NO.34', deliveryCycle: 'biweekly' },
      { name: 'WARUNG MAKMUR JAYA', location: 'JL RAMBUTAN NO.56', deliveryCycle: 'weekly' },

      // Chain stores (20% = ~22 customers)
      {
        name: 'INDOMARET GORONTALO 1',
        location: 'JL AHMAD YANI NO.123',
        deliveryCycle: 'biweekly',
      },
      { name: 'INDOMARET GORONTALO 2', location: 'JL SUDIRMAN NO.45', deliveryCycle: 'biweekly' },
      {
        name: 'INDOMARET GORONTALO 3',
        location: 'JL NANI WARTABONE NO.67',
        deliveryCycle: 'weekly',
      },
      { name: 'INDOMARET GORONTALO 4', location: 'JL HB JASSIN NO.89', deliveryCycle: 'weekly' },
      { name: 'INDOMARET GORONTALO 5', location: 'JL 23 JANUARI NO.12', deliveryCycle: 'biweekly' },
      { name: 'INDOMARET GORONTALO 6', location: 'JL PANJAITAN NO.34', deliveryCycle: 'monthly' },
      { name: 'ALFAMART GORONTALO 1', location: 'JL AGUS SALIM NO.56', deliveryCycle: 'weekly' },
      {
        name: 'ALFAMART GORONTALO 2',
        location: 'JL DEWI SARTIKA NO.78',
        deliveryCycle: 'biweekly',
      },
      { name: 'ALFAMART GORONTALO 3', location: 'JL ANDALAS NO.90', deliveryCycle: 'monthly' },
      { name: 'ALFAMART GORONTALO 4', location: 'JL BUDI UTOMO NO.12', deliveryCycle: 'monthly' },
      { name: 'ALFAMART GORONTALO 5', location: 'JL JAKARTA NO.34', deliveryCycle: 'weekly' },
      {
        name: 'ALFAMART GORONTALO 6',
        location: 'JL ACHMAD NADJAMUDDIN NO.56',
        deliveryCycle: 'biweekly',
      },
      {
        name: 'CIRCLE K GORONTALO 1',
        location: 'JL SAMRATULANGI NO.78',
        deliveryCycle: 'biweekly',
      },
      {
        name: 'CIRCLE K GORONTALO 2',
        location: 'JL SULTAN BOTUTIHE NO.90',
        deliveryCycle: 'biweekly',
      },
      {
        name: 'CIRCLE K GORONTALO 3',
        location: 'JL WOLTER MONGINSIDI NO.12',
        deliveryCycle: 'biweekly',
      },
      { name: 'LAWSON GORONTALO 1', location: 'JL AHMAD YANI NO.34', deliveryCycle: 'weekly' },
      { name: 'LAWSON GORONTALO 2', location: 'JL PERTIWI NO.56', deliveryCycle: 'biweekly' },
      { name: 'LAWSON GORONTALO 3', location: 'JL SAWIT NO.78', deliveryCycle: 'monthly' },
      { name: 'FAMILY MART GORONTALO 1', location: 'JL RAMBUTAN NO.90', deliveryCycle: 'monthly' },
      { name: 'FAMILY MART GORONTALO 2', location: 'JL DURIAN NO.12', deliveryCycle: 'monthly' },
      { name: 'FAMILY MART GORONTALO 3', location: 'JL MANGGA NO.34', deliveryCycle: 'weekly' },
      { name: 'FAMILY MART GORONTALO 4', location: 'JL JERUK NO.56', deliveryCycle: 'monthly' },

      // Mini markets (30% = ~33 customers)
      { name: 'MINI MARKET CENTRAL', location: 'JL NANAS NO.78', deliveryCycle: 'weekly' },
      { name: 'FRESH MART GORONTALO', location: 'JL KELAPA NO.90', deliveryCycle: 'weekly' },
      { name: 'MULTI MART', location: 'JL PISANG NO.12', deliveryCycle: 'biweekly' },
      { name: 'SMART MART', location: 'JL MANGGIS NO.34', deliveryCycle: 'biweekly' },
      { name: 'MEGA MART', location: 'JL SULTAN HASANUDDIN NO.56', deliveryCycle: 'monthly' },
      { name: 'STAR MART', location: 'JL RAJAWALI NO.78', deliveryCycle: 'biweekly' },
      { name: 'FAMILY MART', location: 'JL MERDEKA NO.90', deliveryCycle: 'biweekly' },
      { name: 'QUICK MART', location: 'JL VETERAN NO.12', deliveryCycle: 'biweekly' },
      { name: 'DAILY MART', location: 'JL PAHLAWAN NO.34', deliveryCycle: 'monthly' },
      { name: 'HAPPY MART', location: 'JL DIPONEGORO NO.56', deliveryCycle: 'monthly' },
      // Add more mini markets to reach ~33 total
      { name: 'MINI MARKET ABADI', location: 'JL GAJAH MADA NO.78', deliveryCycle: 'monthly' },
      {
        name: 'MINI MARKET SEJAHTERA',
        location: 'JL SULTAN BOTUTIHE NO.90',
        deliveryCycle: 'weekly',
      },
      {
        name: 'MINI MARKET BERKAH',
        location: 'JL WOLTER MONGINSIDI NO.12',
        deliveryCycle: 'monthly',
      },
      { name: 'MINI MARKET JAYA', location: 'JL AHMAD YANI NO.34', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET MAKMUR', location: 'JL PERTIWI NO.56', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET SENTOSA', location: 'JL SAWIT NO.78', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET BAROKAH', location: 'JL RAMBUTAN NO.90', deliveryCycle: 'biweekly' },
      { name: 'MINI MARKET ABADI', location: 'JL DURIAN NO.12', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET SEJATI', location: 'JL MANGGA NO.34', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET MAJU', location: 'JL JERUK NO.56', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET JAYA', location: 'JL NANAS NO.78', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET BERKAH', location: 'JL KELAPA NO.90', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET MAKMUR', location: 'JL PISANG NO.12', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET SENTOSA', location: 'JL MANGGIS NO.34', deliveryCycle: 'monthly' },
      {
        name: 'MINI MARKET BAROKAH',
        location: 'JL SULTAN HASANUDDIN NO.56',
        deliveryCycle: 'biweekly',
      },
      { name: 'MINI MARKET ABADI', location: 'JL RAJAWALI NO.78', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET SEJATI', location: 'JL MERDEKA NO.90', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET MAJU', location: 'JL VETERAN NO.12', deliveryCycle: 'biweekly' },
      { name: 'MINI MARKET JAYA', location: 'JL PAHLAWAN NO.34', deliveryCycle: 'biweekly' },
      { name: 'MINI MARKET BERKAH', location: 'JL DIPONEGORO NO.56', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET MAKMUR', location: 'JL GAJAH MADA NO.78', deliveryCycle: 'monthly' },
      {
        name: 'MINI MARKET SENTOSA',
        location: 'JL SULTAN BOTUTIHE NO.90',
        deliveryCycle: 'biweekly',
      },
      {
        name: 'MINI MARKET BAROKAH',
        location: 'JL WOLTER MONGINSIDI NO.12',
        deliveryCycle: 'weekly',
      },

      // Grosir/wholesale (10% = ~11 customers)
      { name: 'GROSIR MAKMUR JAYA', location: 'JL AHMAD YANI NO.100', deliveryCycle: 'weekly' },
      { name: 'GROSIR SEJAHTERA', location: 'JL SUDIRMAN NO.200', deliveryCycle: 'weekly' },
      { name: 'GROSIR ABADI', location: 'JL NANI WARTABONE NO.150', deliveryCycle: 'monthly' },
      { name: 'GROSIR MAJU BERSAMA', location: 'JL HB JASSIN NO.300', deliveryCycle: 'biweekly' },
      { name: 'GROSIR BERKAH', location: 'JL 23 JANUARI NO.250', deliveryCycle: 'weekly' },
      { name: 'GROSIR JAYA', location: 'JL PANJAITAN NO.350', deliveryCycle: 'monthly' },
      { name: 'GROSIR MAKMUR', location: 'JL AGUS SALIM NO.400', deliveryCycle: 'weekly' },
      { name: 'GROSIR SEJATI', location: 'JL DEWI SARTIKA NO.450', deliveryCycle: 'monthly' },
      { name: 'GROSIR SENTOSA', location: 'JL ANDALAS NO.500', deliveryCycle: 'biweekly' },
      { name: 'GROSIR UTAMA', location: 'JL BUDI UTOMO NO.550', deliveryCycle: 'weekly' },
      { name: 'GROSIR BAROKAH', location: 'JL JAKARTA NO.600', deliveryCycle: 'monthly' },
    ],
  },
  'RDA JEMBER': {
    region: 'JAWA TIMUR',
    coordinates: {
      center: {
        lat: -8.2612353,
        lng: 113.6502499,
      },
      radius: 45,
    },
    vehicles: ['B9704NCJ', 'B9620SCN', 'B9345NCJ', 'B9678SCN', 'B9890NCJ'],
    drivers: [
      { name: 'ARIF EFENDI', helper: 'ATHOK' },
      { name: 'FAQIH', helper: 'FERDI' },
      { name: 'HASAN', helper: 'DEDI' },
      { name: 'BAMBANG', helper: 'AGUS' },
      { name: 'YUSUF', helper: 'ANDI' },
    ],
    customers: [
      // Local stores/warung (40% = ~44 customers)
      { name: 'B YUDI', location: 'JL PASAR JENGAWAH NO.12', deliveryCycle: 'weekly' },
      {
        name: 'PT. INDOMARCO PRISMATAMA',
        location: 'JL PIERE TENDEAN SUMBERSARI NO.34',
        deliveryCycle: 'weekly',
      },
      { name: 'PANCA JAUA', location: 'JL PANTI NO.56', deliveryCycle: 'biweekly' },
      { name: 'NADIA', location: 'JL DUSUN KANTONG NO.78', deliveryCycle: 'weekly' },
      { name: 'WARUNG BERKAH', location: 'JL GAJAH MADA NO.90', deliveryCycle: 'biweekly' },
      { name: 'TOKO SEJAHTERA', location: 'JL KALIMANTAN NO.12', deliveryCycle: 'biweekly' },
      { name: 'WARUNG MAKMUR', location: 'JL MASTRIP NO.34', deliveryCycle: 'weekly' },
      { name: 'TOKO BAROKAH', location: 'JL BRAWIJAYA NO.56', deliveryCycle: 'biweekly' },
      { name: 'WARUNG REZEKI', location: 'JL AHMAD YANI NO.78', deliveryCycle: 'biweekly' },
      { name: 'TOKO JAYA', location: 'JL SUDIRMAN NO.90', deliveryCycle: 'monthly' },

      // Add more local stores to reach ~44 total
      { name: 'WARUNG ABADI', location: 'JL KARIMATA NO.12', deliveryCycle: 'monthly' },
      { name: 'TOKO SINAR JAYA', location: 'JL MAWAR NO.34', deliveryCycle: 'monthly' },
      { name: 'WARUNG BERKAH', location: 'JL HAYAM WURUK NO.56', deliveryCycle: 'biweekly' },
      { name: 'TOKO SEJAHTERA', location: 'JL LETJEN PANJAITAN NO.78', deliveryCycle: 'weekly' },
      { name: 'WARUNG MAJU MAKMUR', location: 'JL PATRANG NO.90', deliveryCycle: 'biweekly' },
      { name: 'TOKO JAYA ABADI', location: 'JL SUMBERSARI NO.12', deliveryCycle: 'biweekly' },
      { name: 'WARUNG BERKAH ABADI', location: 'JL KALIWATES NO.34', deliveryCycle: 'weekly' },
      { name: 'TOKO BERKAH UTAMA', location: 'JL TANGGUL NO.56', deliveryCycle: 'weekly' },
      { name: 'WARUNG JAYA MAKMUR', location: 'JL AMBULU NO.78', deliveryCycle: 'monthly' },
      { name: 'TOKO SEJAHTERA ABADI', location: 'JL RAMBIPUJI NO.90', deliveryCycle: 'monthly' },
      { name: 'WARUNG SINAR SEJAHTERA', location: 'JL WULUHAN NO.12', deliveryCycle: 'biweekly' },
      { name: 'TOKO MAKMUR JAYA', location: 'JL BALUNG NO.34', deliveryCycle: 'weekly' },
      { name: 'WARUNG SUKSES JAYA', location: 'JL UMBULSARI NO.56', deliveryCycle: 'biweekly' },
      { name: 'TOKO ABADI MAKMUR', location: 'JL SEMBORO NO.78', deliveryCycle: 'monthly' },
      { name: 'WARUNG JAYA MANDIRI', location: 'JL SUKOWONO NO.90', deliveryCycle: 'weekly' },
      { name: 'TOKO SINAR HARAPAN', location: 'JL JELBUK NO.12', deliveryCycle: 'weekly' },
      { name: 'WARUNG BERKAH JAYA', location: 'JL PAKUSARI NO.34', deliveryCycle: 'weekly' },
      { name: 'TOKO MAKMUR SEJAHTERA', location: 'JL SUKORAMBI NO.56', deliveryCycle: 'biweekly' },
      { name: 'WARUNG ABADI SENTOSA', location: 'JL ARJASA NO.78', deliveryCycle: 'weekly' },
      { name: 'TOKO SINAR TERANG', location: 'JL SUMBERJAMBE NO.90', deliveryCycle: 'monthly' },
      { name: 'WARUNG MAJU JAYA', location: 'JL LEDOKOMBO NO.12', deliveryCycle: 'monthly' },
      { name: 'TOKO BERKAH ABADI', location: 'JL KALISAT NO.34', deliveryCycle: 'monthly' },
      { name: 'WARUNG SEJAHTERA', location: 'JL SUMBERBARU NO.56', deliveryCycle: 'monthly' },
      { name: 'TOKO MAKMUR JAYA', location: 'JL TANGGUL NO.78', deliveryCycle: 'monthly' },
      { name: 'WARUNG BAROKAH', location: 'JL BANGSALSARI NO.90', deliveryCycle: 'biweekly' },
      { name: 'TOKO SINAR ABADI', location: 'JL PANTI NO.12', deliveryCycle: 'biweekly' },
      { name: 'WARUNG BERKAH', location: 'JL SUKORAMBI NO.34', deliveryCycle: 'biweekly' },
      { name: 'TOKO MAKMUR SEJATI', location: 'JL PATRANG NO.56', deliveryCycle: 'biweekly' },
      { name: 'WARUNG JAYA MAKMUR', location: 'JL SUMBERSARI NO.78', deliveryCycle: 'weekly' },
      { name: 'TOKO ABADI JAYA', location: 'JL KALIWATES NO.90', deliveryCycle: 'weekly' },
      { name: 'WARUNG SUMBER REJEKI', location: 'JL RAMBIPUJI NO.12', deliveryCycle: 'weekly' },
      { name: 'TOKO BERKAH UTAMA', location: 'JL WULUHAN NO.34', deliveryCycle: 'monthly' },
      { name: 'WARUNG MAKMUR JAYA', location: 'JL BALUNG NO.56', deliveryCycle: 'biweekly' },
      { name: 'TOKO SEJAHTERA', location: 'JL UMBULSARI NO.78', deliveryCycle: 'biweekly' },

      // Chain stores (20% = ~22 customers)
      { name: 'INDOMARET JEMBER 1', location: 'JL GAJAH MADA NO.123', deliveryCycle: 'monthly' },
      { name: 'INDOMARET JEMBER 2', location: 'JL KALIMANTAN NO.45', deliveryCycle: 'weekly' },
      { name: 'INDOMARET JEMBER 3', location: 'JL MASTRIP NO.67', deliveryCycle: 'weekly' },
      { name: 'INDOMARET JEMBER 4', location: 'JL BRAWIJAYA NO.89', deliveryCycle: 'weekly' },
      { name: 'INDOMARET JEMBER 5', location: 'JL AHMAD YANI NO.12', deliveryCycle: 'monthly' },
      { name: 'INDOMARET JEMBER 6', location: 'JL SUDIRMAN NO.34', deliveryCycle: 'monthly' },
      { name: 'ALFAMART JEMBER 1', location: 'JL KARIMATA NO.56', deliveryCycle: 'weekly' },
      { name: 'ALFAMART JEMBER 2', location: 'JL MAWAR NO.78', deliveryCycle: 'biweekly' },
      { name: 'ALFAMART JEMBER 3', location: 'JL HAYAM WURUK NO.90', deliveryCycle: 'biweekly' },
      {
        name: 'ALFAMART JEMBER 4',
        location: 'JL LETJEN PANJAITAN NO.12',
        deliveryCycle: 'monthly',
      },
      { name: 'ALFAMART JEMBER 5', location: 'JL PATRANG NO.34', deliveryCycle: 'monthly' },
      { name: 'ALFAMART JEMBER 6', location: 'JL SUMBERSARI NO.56', deliveryCycle: 'monthly' },
      { name: 'CIRCLE K JEMBER 1', location: 'JL KALIWATES NO.78', deliveryCycle: 'weekly' },
      { name: 'CIRCLE K JEMBER 2', location: 'JL TANGGUL NO.90', deliveryCycle: 'monthly' },
      { name: 'CIRCLE K JEMBER 3', location: 'JL AMBULU NO.12', deliveryCycle: 'biweekly' },
      { name: 'LAWSON JEMBER 1', location: 'JL RAMBIPUJI NO.34', deliveryCycle: 'weekly' },
      { name: 'LAWSON JEMBER 2', location: 'JL WULUHAN NO.56', deliveryCycle: 'monthly' },
      { name: 'LAWSON JEMBER 3', location: 'JL BALUNG NO.78', deliveryCycle: 'weekly' },
      { name: 'FAMILY MART JEMBER 1', location: 'JL UMBULSARI NO.90', deliveryCycle: 'biweekly' },
      { name: 'FAMILY MART JEMBER 2', location: 'JL SEMBORO NO.12', deliveryCycle: 'biweekly' },
      { name: 'FAMILY MART JEMBER 3', location: 'JL SUKOWONO NO.34', deliveryCycle: 'biweekly' },
      { name: 'FAMILY MART JEMBER 4', location: 'JL JELBUK NO.56', deliveryCycle: 'weekly' },

      // Mini markets (30% = ~33 customers)
      { name: 'MINI MARKET CENTRAL', location: 'JL PAKUSARI NO.78', deliveryCycle: 'weekly' },
      { name: 'FRESH MART JEMBER', location: 'JL SUKORAMBI NO.90', deliveryCycle: 'monthly' },
      { name: 'MULTI MART', location: 'JL ARJASA NO.12', deliveryCycle: 'monthly' },
      { name: 'SMART MART', location: 'JL SUMBERJAMBE NO.34', deliveryCycle: 'biweekly' },
      { name: 'MEGA MART', location: 'JL LEDOKOMBO NO.56', deliveryCycle: 'monthly' },
      { name: 'STAR MART', location: 'JL KALISAT NO.78', deliveryCycle: 'biweekly' },
      { name: 'FAMILY MART', location: 'JL SUMBERBARU NO.90', deliveryCycle: 'monthly' },
      { name: 'QUICK MART', location: 'JL TANGGUL NO.12', deliveryCycle: 'monthly' },
      { name: 'DAILY MART', location: 'JL BANGSALSARI NO.34', deliveryCycle: 'monthly' },
      { name: 'HAPPY MART', location: 'JL PANTI NO.56', deliveryCycle: 'weekly' },
      // Add more mini markets to reach ~33 total
      { name: 'MINI MARKET ABADI', location: 'JL SUKORAMBI NO.78', deliveryCycle: 'biweekly' },
      { name: 'MINI MARKET SEJAHTERA', location: 'JL PATRANG NO.90', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET BERKAH', location: 'JL SUMBERSARI NO.12', deliveryCycle: 'biweekly' },
      { name: 'MINI MARKET JAYA', location: 'JL KALIWATES NO.34', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET MAKMUR', location: 'JL RAMBIPUJI NO.56', deliveryCycle: 'biweekly' },
      { name: 'MINI MARKET SENTOSA', location: 'JL WULUHAN NO.78', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET BAROKAH', location: 'JL BALUNG NO.90', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET ABADI', location: 'JL UMBULSARI NO.12', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET SEJATI', location: 'JL SEMBORO NO.34', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET MAJU', location: 'JL SUKOWONO NO.56', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET JAYA', location: 'JL JELBUK NO.78', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET BERKAH', location: 'JL PAKUSARI NO.90', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET MAKMUR', location: 'JL SUKORAMBI NO.12', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET SENTOSA', location: 'JL ARJASA NO.34', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET BAROKAH', location: 'JL SUMBERJAMBE NO.56', deliveryCycle: 'biweekly' },
      { name: 'MINI MARKET ABADI', location: 'JL LEDOKOMBO NO.78', deliveryCycle: 'biweekly' },
      { name: 'MINI MARKET SEJATI', location: 'JL KALISAT NO.90', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET MAJU', location: 'JL SUMBERBARU NO.12', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET JAYA', location: 'JL TANGGUL NO.34', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET BERKAH', location: 'JL BANGSALSARI NO.56', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET MAKMUR', location: 'JL PANTI NO.78', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET SENTOSA', location: 'JL SUKORAMBI NO.90', deliveryCycle: 'biweekly' },
      { name: 'MINI MARKET BAROKAH', location: 'JL PATRANG NO.12', deliveryCycle: 'monthly' },

      // Grosir/wholesale (10% = ~11 customers)
      { name: 'GROSIR MAKMUR JAYA', location: 'JL GAJAH MADA NO.100', deliveryCycle: 'monthly' },
      { name: 'GROSIR SEJAHTERA', location: 'JL KALIMANTAN NO.200', deliveryCycle: 'biweekly' },
      { name: 'GROSIR ABADI', location: 'JL MASTRIP NO.150', deliveryCycle: 'monthly' },
      { name: 'GROSIR MAJU BERSAMA', location: 'JL BRAWIJAYA NO.300', deliveryCycle: 'weekly' },
      { name: 'GROSIR BERKAH', location: 'JL AHMAD YANI NO.250', deliveryCycle: 'weekly' },
      { name: 'GROSIR JAYA', location: 'JL SUDIRMAN NO.350', deliveryCycle: 'weekly' },
      { name: 'GROSIR MAKMUR', location: 'JL KARIMATA NO.400', deliveryCycle: 'weekly' },
      { name: 'GROSIR SEJATI', location: 'JL MAWAR NO.450', deliveryCycle: 'biweekly' },
      { name: 'GROSIR SENTOSA', location: 'JL HAYAM WURUK NO.500', deliveryCycle: 'monthly' },
      { name: 'GROSIR UTAMA', location: 'JL LETJEN PANJAITAN NO.550', deliveryCycle: 'monthly' },
      { name: 'GROSIR BAROKAH', location: 'JL PATRANG NO.600', deliveryCycle: 'biweekly' },
    ],
  },
  'RDA CIANJUR': {
    region: 'JAWA BARAT',
    coordinates: {
      center: {
        lat: -6.827335,
        lng: 107.15058,
      },
      radius: 45,
    },
    vehicles: ['B9460SCN', 'B9567NCJ', 'B9890SCN', 'B9234NCJ'],
    drivers: [
      { name: 'HAERUDIN', helper: 'INDRA' },
      { name: 'ASEP', helper: 'DEDI' },
      { name: 'UJANG', helper: 'CECEP' },
      { name: 'DADANG', helper: 'AGUS' },
    ],
    customers: [
      // Local stores/warung (40% = ~44 customers)
      { name: 'H IYAN', location: 'JL TUGU MUNJUL NO.12', deliveryCycle: 'weekly' },
      { name: 'ANDRE', location: 'JL HALTE MALEBER NO.34', deliveryCycle: 'monthly' },
      { name: 'SALWA', location: 'JL HALTE MALEBER NO.56', deliveryCycle: 'biweekly' },
      { name: 'SRC MAMAT', location: 'JL MALEBER NO.78', deliveryCycle: 'monthly' },
      { name: 'WARUNG BERKAH', location: 'JL IR H JUANDA NO.90', deliveryCycle: 'monthly' },
      { name: 'TOKO SEJAHTERA', location: 'JL SILIWANGI NO.12', deliveryCycle: 'monthly' },
      { name: 'WARUNG MAKMUR', location: 'JL DR MUWARDI NO.34', deliveryCycle: 'weekly' },
      { name: 'TOKO BAROKAH', location: 'JL ABDULLAH BIN NUH NO.56', deliveryCycle: 'weekly' },
      { name: 'WARUNG REZEKI', location: 'JL RAYA BANDUNG NO.78', deliveryCycle: 'monthly' },
      { name: 'TOKO JAYA', location: 'JL RAYA SUKABUMI NO.90', deliveryCycle: 'biweekly' },
      // Add more local stores to reach ~44 total
      { name: 'WARUNG BERSAMA', location: 'JL IR H JUANDA NO.90', deliveryCycle: 'biweekly' },
      { name: 'TOKO SEJAHTERA', location: 'JL SILIWANGI NO.12', deliveryCycle: 'biweekly' },
      { name: 'WARUNG MAKMUR', location: 'JL DR MUWARDI NO.34', deliveryCycle: 'weekly' },
      { name: 'TOKO BAROKAH', location: 'JL ABDULLAH BIN NUH NO.56', deliveryCycle: 'biweekly' },
      { name: 'WARUNG REZEKI', location: 'JL RAYA BANDUNG NO.78', deliveryCycle: 'weekly' },
      { name: 'TOKO JAYA', location: 'JL RAYA SUKABUMI NO.90', deliveryCycle: 'weekly' },
      { name: 'WARUNG ABADI', location: 'JL PASAR BARU NO.12', deliveryCycle: 'weekly' },
      { name: 'TOKO SENTOSA', location: 'JL RAYA CIHERANG NO.25', deliveryCycle: 'biweekly' },
      { name: 'TOKO GEMILANG', location: 'JL CIPUTRI NO.5', deliveryCycle: 'monthly' },
      { name: 'WARUNG NUSA', location: 'JL RAYA CIPUTRI NO.10', deliveryCycle: 'weekly' },
      { name: 'TOKO ANUGRAH', location: 'JL RAYA BANDUNG NO.50', deliveryCycle: 'weekly' },
      { name: 'WARUNG PERMATA', location: 'JL CIPANAS NO.40', deliveryCycle: 'monthly' },
      { name: 'TOKO MUTIARA', location: 'JL RAYA CIANJUR NO.30', deliveryCycle: 'monthly' },
      { name: 'WARUNG NUSANTARA', location: 'JL CIPUTRI NO.22', deliveryCycle: 'biweekly' },
      { name: 'TOKO KENCANA', location: 'JL SUKAMULYA NO.33', deliveryCycle: 'monthly' },
      { name: 'WARUNG MELATI', location: 'JL KARANGTENGAH NO.8', deliveryCycle: 'weekly' },
      { name: 'WARUNG CERIA', location: 'JL PANGERAN HARYA NO.18', deliveryCycle: 'weekly' },
      { name: 'WARUNG SERASI', location: 'JL DR MUWARDI NO.44', deliveryCycle: 'weekly' },
      { name: 'WARUNG HARAPAN', location: 'JL PASIR HAYAM NO.20', deliveryCycle: 'monthly' },
      { name: 'TOKO AMANAH', location: 'JL KARANGTENGAH NO.15', deliveryCycle: 'monthly' },
      { name: 'WARUNG RAHAYU', location: 'JL RAYA SUKAMULYA NO.48', deliveryCycle: 'monthly' },
      { name: 'TOKO JAYA RAYA', location: 'JL CIPUTRI NO.60', deliveryCycle: 'biweekly' },
      { name: 'WARUNG NIRMALA', location: 'JL SUKABUMI NO.22', deliveryCycle: 'biweekly' },
      { name: 'TOKO BINA USAHA', location: 'JL PANGERAN HARYA NO.5', deliveryCycle: 'weekly' },
      { name: 'WARUNG LESTARI', location: 'JL CIPUTRI NO.18', deliveryCycle: 'weekly' },
      { name: 'TOKO SUMBER REZEKI', location: 'JL CIANJUR NO.42', deliveryCycle: 'weekly' },
      { name: 'WARUNG MURNI', location: 'JL CIPANAS NO.12', deliveryCycle: 'monthly' },
      { name: 'TOKO INTAN', location: 'JL RAYA CIHERANG NO.33', deliveryCycle: 'biweekly' },
      { name: 'WARUNG PERTIWI', location: 'JL DR MUWARDI NO.15', deliveryCycle: 'monthly' },
      { name: 'WARUNG KARYA', location: 'JL CIPUTRI NO.25', deliveryCycle: 'weekly' },
      { name: 'TOKO KASIH SAYANG', location: 'JL SUKABUMI NO.40', deliveryCycle: 'monthly' },
      { name: 'WARUNG SURYA', location: 'JL CIPANAS NO.5', deliveryCycle: 'weekly' },
      { name: 'TOKO ASIH', location: 'JL RAYA SUKAMULYA NO.38', deliveryCycle: 'biweekly' },
      { name: 'WARUNG WIJAYA', location: 'JL KARANGTENGAH NO.25', deliveryCycle: 'biweekly' },
      { name: 'TOKO BERSINAR', location: 'JL CIPUTRI NO.12', deliveryCycle: 'monthly' },
      { name: 'WARUNG MANDIRI', location: 'JL SUKABUMI NO.50', deliveryCycle: 'weekly' },
      { name: 'TOKO GEMILANG JAYA', location: 'JL CIANJUR NO.20', deliveryCycle: 'biweekly' },
      { name: 'WARUNG PERDANA', location: 'JL PANGERAN HARYA NO.40', deliveryCycle: 'weekly' },
      { name: 'TOKO HARMONI', location: 'JL DR MUWARDI NO.33', deliveryCycle: 'biweekly' },
      { name: 'WARUNG DAMAI', location: 'JL RAYA PASIR HAYAM NO.10', deliveryCycle: 'weekly' },
      { name: 'TOKO SEJATI', location: 'JL CIHERANG NO.18', deliveryCycle: 'monthly' },
      { name: 'WARUNG BUDI', location: 'JL SILIWANGI NO.5', deliveryCycle: 'biweekly' },
      { name: 'WARUNG SENTOSA', location: 'JL CIPUTRI NO.35', deliveryCycle: 'monthly' },
      { name: 'TOKO ANUGERAH', location: 'JL KARANGTENGAH NO.50', deliveryCycle: 'monthly' },
      { name: 'WARUNG KENCANA', location: 'JL CIPANAS NO.28', deliveryCycle: 'weekly' },
      { name: 'TOKO LESTARI JAYA', location: 'JL CIPUTRI NO.15', deliveryCycle: 'monthly' },
      { name: 'WARUNG HATI MULIA', location: 'JL SUKABUMI NO.44', deliveryCycle: 'weekly' },
      { name: 'TOKO NUSA INDAH', location: 'JL DR MUWARDI NO.12', deliveryCycle: 'weekly' },
      { name: 'WARUNG RAYA', location: 'JL CIANJUR NO.25', deliveryCycle: 'monthly' },
      { name: 'TOKO PERMAI', location: 'JL CIPUTRI NO.22', deliveryCycle: 'weekly' },
      { name: 'WARUNG GEMILANG', location: 'JL SUKAMULYA NO.15', deliveryCycle: 'weekly' },
      { name: 'TOKO ARTHA JAYA', location: 'JL CIHERANG NO.33', deliveryCycle: 'biweekly' },
      { name: 'WARUNG PERSADA', location: 'JL SILIWANGI NO.22', deliveryCycle: 'biweekly' },
      { name: 'TOKO PUTRA MANDIRI', location: 'JL PASIR HAYAM NO.18', deliveryCycle: 'biweekly' },
      { name: 'WARUNG INDAH', location: 'JL CIPUTRI NO.45', deliveryCycle: 'weekly' },
      { name: 'TOKO ALAM INDAH', location: 'JL DR MUWARDI NO.55', deliveryCycle: 'biweekly' },
      { name: 'WARUNG MULIA', location: 'JL SUKAMULYA NO.30', deliveryCycle: 'monthly' },
      { name: 'TOKO BERLIAN', location: 'JL CIPANAS NO.18', deliveryCycle: 'monthly' },
      { name: 'WARUNG MEGAH', location: 'JL CIANJUR NO.60', deliveryCycle: 'biweekly' },
      // Mini Markets (~33 customers)
      { name: 'MINIMARKET FAMILI', location: 'JL IR H JUANDA NO.1', deliveryCycle: 'weekly' },
      { name: 'MINIMARKET PRIMA', location: 'JL ABDULLAH BIN NUH NO.22', deliveryCycle: 'weekly' },
      { name: 'MINIMARKET SAHABAT', location: 'JL KH M ASYARI NO.35', deliveryCycle: 'weekly' },
      { name: 'MINIMARKET SURYA', location: 'JL PANGERAN HARYA NO.18', deliveryCycle: 'monthly' },
      { name: 'MINIMARKET MITRA', location: 'JL RAYA CIPANAS NO.40', deliveryCycle: 'biweekly' },
      { name: 'MINIMARKET CERIA', location: 'JL KARANGTENGAH NO.10', deliveryCycle: 'weekly' },
      { name: 'MINIMARKET BERSAMA', location: 'JL CIPUTRI NO.50', deliveryCycle: 'weekly' },
      { name: 'MINIMARKET BERKAH', location: 'JL RAYA SUKAMULYA NO.12', deliveryCycle: 'weekly' },
      { name: 'MINIMARKET INDAH', location: 'JL RAYA CIANJUR NO.33', deliveryCycle: 'monthly' },
      { name: 'MINIMARKET MAJU JAYA', location: 'JL DR MUWARDI NO.8', deliveryCycle: 'weekly' },
      { name: 'MINIMARKET MANDIRI', location: 'JL CIBEBER NO.5', deliveryCycle: 'weekly' },
      { name: 'MINIMARKET LESTARI', location: 'JL SUKABUMI NO.15', deliveryCycle: 'weekly' },
      { name: 'MINIMARKET ASRI', location: 'JL IR H JUANDA NO.22', deliveryCycle: 'monthly' },
      {
        name: 'MINIMARKET MUTIARA',
        location: 'JL KH ABDULLAH BIN NUH NO.8',
        deliveryCycle: 'monthly',
      },
      { name: 'MINIMARKET SEJAHTERA', location: 'JL CIPUTRI NO.28', deliveryCycle: 'biweekly' },
      { name: 'MINIMARKET SENTOSA', location: 'JL CIPUTRI NO.33', deliveryCycle: 'monthly' },
      { name: 'MINIMARKET RAHARJA', location: 'JL SUKAMULYA NO.50', deliveryCycle: 'monthly' },
      { name: 'MINIMARKET GEMILANG', location: 'JL DR MUWARDI NO.42', deliveryCycle: 'monthly' },
      {
        name: 'MINIMARKET KENCANA',
        location: 'JL RAYA KARANGTENGAH NO.10',
        deliveryCycle: 'monthly',
      },
      { name: 'MINIMARKET MELATI', location: 'JL CIPANAS NO.5', deliveryCycle: 'weekly' },
      { name: 'MINIMARKET CEMERLANG', location: 'JL CIPUTRI NO.8', deliveryCycle: 'monthly' },
      { name: 'MINIMARKET BINTANG', location: 'JL CIHERANG NO.3', deliveryCycle: 'biweekly' },
      { name: 'MINIMARKET LESTARI', location: 'JL CIANJUR NO.25', deliveryCycle: 'weekly' },
      { name: 'MINIMARKET ARTHA', location: 'JL SUKABUMI NO.18', deliveryCycle: 'biweekly' },

      // Chain Stores (20% = ~22 customers)
      {
        name: 'ALFAMART PASIR HAYAM',
        location: 'JL RAYA PASIR HAYAM NO.10',
        deliveryCycle: 'weekly',
      },
      { name: 'INDOMARET CIPUTRI', location: 'JL CIPUTRI NO.12', deliveryCycle: 'monthly' },
      {
        name: 'ALFAMART SUKAMULYA',
        location: 'JL RAYA SUKAMULYA NO.33',
        deliveryCycle: 'biweekly',
      },
      { name: 'INDOMARET CIPANAS', location: 'JL CIPANAS NO.45', deliveryCycle: 'monthly' },
      {
        name: 'ALFAMART KARANGTENGAH',
        location: 'JL RAYA KARANGTENGAH NO.8',
        deliveryCycle: 'biweekly',
      },
      { name: 'INDOMARET MALEBER', location: 'JL HALTE MALEBER NO.20', deliveryCycle: 'weekly' },
      { name: 'ALFAMART SILIWANGI', location: 'JL SILIWANGI NO.10', deliveryCycle: 'biweekly' },
      { name: 'INDOMARET CIHERANG', location: 'JL CIHERANG NO.25', deliveryCycle: 'weekly' },
      { name: 'ALFAMART SUKABUMI', location: 'JL RAYA SUKABUMI NO.50', deliveryCycle: 'biweekly' },
      { name: 'INDOMARET DR MUWARDI', location: 'JL DR MUWARDI NO.12', deliveryCycle: 'biweekly' },
      { name: 'ALFAMART JANGARI', location: 'JL RAYA JANGARI NO.25', deliveryCycle: 'weekly' },
    ],
  },
  'RDA GRESIK': {
    region: 'JAWA TIMUR',
    coordinates: {
      center: {
        lat: -7.1535774,
        lng: 112.5264626,
      },
      radius: 28,
    },
    vehicles: ['B9677NCJ', 'B9692NCJ', 'B9234NCJ', 'B9567NCJ', 'B9890NCJ'],
    drivers: [
      { name: 'MARTIN', helper: 'JUN' },
      { name: 'RAVI', helper: 'TUNJUNG' },
      { name: 'BAMBANG', helper: 'AGUS' },
      { name: 'YUSUF', helper: 'ANDI' },
      { name: 'RAHMAN', helper: 'DEDI' },
    ],
    customers: [
      // Local stores/warung (40% = ~44 customers)
      { name: 'VILLA JAYA', location: 'JL KEMENDUNG NO.12', deliveryCycle: 'biweekly' },
      { name: 'TOKO YUSUF', location: 'JL PASAR DUKUN NO.34', deliveryCycle: 'monthly' },
      { name: 'WARUNG BERKAH', location: 'JL DR WAHIDIN NO.56', deliveryCycle: 'weekly' },
      { name: 'TOKO SEJAHTERA', location: 'JL VETERAN NO.78', deliveryCycle: 'weekly' },
      { name: 'WARUNG MAKMUR', location: 'JL GUBERNUR SURYO NO.90', deliveryCycle: 'monthly' },
      { name: 'TOKO BAROKAH', location: 'JL USMAN SADAR NO.12', deliveryCycle: 'monthly' },
      { name: 'WARUNG REZEKI', location: 'JL SINDUJOYO NO.34', deliveryCycle: 'monthly' },
      { name: 'TOKO JAYA', location: 'JL JAKSA AGUNG SUPRAPTO NO.56', deliveryCycle: 'weekly' },
      { name: 'WARUNG ABADI', location: 'JL SAMANHUDI NO.78', deliveryCycle: 'biweekly' },
      { name: 'TOKO SINAR JAYA', location: 'JL KARTINI NO.90', deliveryCycle: 'biweekly' },
      { name: 'WARUNG BERKAH', location: 'JL PAHLAWAN NO.12', deliveryCycle: 'weekly' },
      { name: 'TOKO SEJAHTERA', location: 'JL KH KHOLIL NO.34', deliveryCycle: 'monthly' },
      {
        name: 'WARUNG MAJU MAKMUR',
        location: 'JL PANGLIMA SUDIRMAN NO.56',
        deliveryCycle: 'weekly',
      },
      { name: 'TOKO JAYA ABADI', location: 'JL AKS TUBUN NO.78', deliveryCycle: 'monthly' },
      {
        name: 'WARUNG BERKAH ABADI',
        location: 'JL MALIK IBRAHIM NO.90',
        deliveryCycle: 'biweekly',
      },
      { name: 'TOKO BERKAH UTAMA', location: 'JL MENGANTI NO.12', deliveryCycle: 'monthly' },
      { name: 'WARUNG JAYA MAKMUR', location: 'JL CERME NO.34', deliveryCycle: 'monthly' },
      { name: 'TOKO SEJAHTERA ABADI', location: 'JL BENJENG NO.56', deliveryCycle: 'biweekly' },
      {
        name: 'WARUNG SINAR SEJAHTERA',
        location: 'JL BALONGPANGGANG NO.78',
        deliveryCycle: 'biweekly',
      },
      { name: 'TOKO MAKMUR JAYA', location: 'JL DUDUKSAMPEYAN NO.90', deliveryCycle: 'monthly' },
      { name: 'WARUNG SUKSES JAYA', location: 'JL KEBOMAS NO.12', deliveryCycle: 'monthly' },
      { name: 'TOKO ABADI MAKMUR', location: 'JL MANYAR NO.34', deliveryCycle: 'monthly' },
      { name: 'WARUNG JAYA MANDIRI', location: 'JL BUNGAH NO.56', deliveryCycle: 'weekly' },
      { name: 'TOKO SINAR HARAPAN', location: 'JL SIDAYU NO.78', deliveryCycle: 'monthly' },
      { name: 'WARUNG BERKAH JAYA', location: 'JL DUKUN NO.90', deliveryCycle: 'monthly' },
      { name: 'TOKO MAKMUR SEJAHTERA', location: 'JL PANCENG NO.12', deliveryCycle: 'biweekly' },
      { name: 'WARUNG ABADI SENTOSA', location: 'JL UJUNGPANGKAH NO.34', deliveryCycle: 'monthly' },
      { name: 'TOKO SINAR TERANG', location: 'JL SANGKAPURA NO.56', deliveryCycle: 'monthly' },
      { name: 'WARUNG MAJU JAYA', location: 'JL TAMBAK NO.78', deliveryCycle: 'weekly' },
      { name: 'TOKO BERKAH ABADI', location: 'JL WRINGINANOM NO.90', deliveryCycle: 'monthly' },
      { name: 'WARUNG SEJAHTERA', location: 'JL DRIYOREJO NO.12', deliveryCycle: 'biweekly' },
      { name: 'TOKO MAKMUR JAYA', location: 'JL KEDAMEAN NO.34', deliveryCycle: 'biweekly' },
      { name: 'WARUNG BAROKAH', location: 'JL MENGARE NO.56', deliveryCycle: 'biweekly' },
      { name: 'TOKO SINAR ABADI', location: 'JL SEMBAYAT NO.78', deliveryCycle: 'biweekly' },
      { name: 'WARUNG BERKAH', location: 'JL CAMPUREJO NO.90', deliveryCycle: 'biweekly' },
      { name: 'TOKO MAKMUR SEJATI', location: 'JL SUKOMULYO NO.12', deliveryCycle: 'biweekly' },
      { name: 'WARUNG JAYA MAKMUR', location: 'JL ROOMO NO.34', deliveryCycle: 'biweekly' },
      { name: 'TOKO ABADI JAYA', location: 'JL SEGOROMADU NO.56', deliveryCycle: 'biweekly' },
      { name: 'WARUNG SUMBER REJEKI', location: 'JL INDRO NO.78', deliveryCycle: 'weekly' },
      { name: 'TOKO BERKAH UTAMA', location: 'JL RANDUAGUNG NO.90', deliveryCycle: 'weekly' },
      { name: 'WARUNG MAKMUR JAYA', location: 'JL PETROKIMIA NO.12', deliveryCycle: 'monthly' },
      { name: 'TOKO SEJAHTERA', location: 'JL GKB NO.34', deliveryCycle: 'monthly' },
      { name: 'WARUNG BAROKAH', location: 'JL KOTA BARU NO.56', deliveryCycle: 'biweekly' },

      // Chain stores (20% = ~22 customers)
      { name: 'INDOMARET GRESIK 1', location: 'JL DR WAHIDIN NO.123', deliveryCycle: 'monthly' },
      { name: 'INDOMARET GRESIK 2', location: 'JL VETERAN NO.45', deliveryCycle: 'biweekly' },
      {
        name: 'INDOMARET GRESIK 3',
        location: 'JL GUBERNUR SURYO NO.67',
        deliveryCycle: 'biweekly',
      },
      { name: 'INDOMARET GRESIK 4', location: 'JL USMAN SADAR NO.89', deliveryCycle: 'biweekly' },
      { name: 'INDOMARET GRESIK 5', location: 'JL SINDUJOYO NO.12', deliveryCycle: 'weekly' },
      {
        name: 'INDOMARET GRESIK 6',
        location: 'JL JAKSA AGUNG SUPRAPTO NO.34',
        deliveryCycle: 'biweekly',
      },
      { name: 'ALFAMART GRESIK 1', location: 'JL SAMANHUDI NO.56', deliveryCycle: 'weekly' },
      { name: 'ALFAMART GRESIK 2', location: 'JL KARTINI NO.78', deliveryCycle: 'biweekly' },
      { name: 'ALFAMART GRESIK 3', location: 'JL PAHLAWAN NO.90', deliveryCycle: 'monthly' },
      { name: 'ALFAMART GRESIK 4', location: 'JL KH KHOLIL NO.12', deliveryCycle: 'weekly' },
      {
        name: 'ALFAMART GRESIK 5',
        location: 'JL PANGLIMA SUDIRMAN NO.34',
        deliveryCycle: 'monthly',
      },
      { name: 'ALFAMART GRESIK 6', location: 'JL AKS TUBUN NO.56', deliveryCycle: 'biweekly' },
      { name: 'CIRCLE K GRESIK 1', location: 'JL MALIK IBRAHIM NO.78', deliveryCycle: 'monthly' },
      { name: 'CIRCLE K GRESIK 2', location: 'JL MENGANTI NO.90', deliveryCycle: 'weekly' },
      { name: 'CIRCLE K GRESIK 3', location: 'JL CERME NO.12', deliveryCycle: 'biweekly' },
      { name: 'LAWSON GRESIK 1', location: 'JL BENJENG NO.34', deliveryCycle: 'biweekly' },
      { name: 'LAWSON GRESIK 2', location: 'JL BALONGPANGGANG NO.56', deliveryCycle: 'monthly' },
      { name: 'LAWSON GRESIK 3', location: 'JL DUDUKSAMPEYAN NO.78', deliveryCycle: 'biweekly' },
      { name: 'FAMILY MART GRESIK 1', location: 'JL KEBOMAS NO.90', deliveryCycle: 'biweekly' },
      { name: 'FAMILY MART GRESIK 2', location: 'JL MANYAR NO.12', deliveryCycle: 'biweekly' },
      { name: 'FAMILY MART GRESIK 3', location: 'JL BUNGAH NO.34', deliveryCycle: 'monthly' },
      { name: 'FAMILY MART GRESIK 4', location: 'JL SIDAYU NO.56', deliveryCycle: 'monthly' },

      // Mini markets (30% = ~33 customers)
      { name: 'MINI MARKET CENTRAL', location: 'JL DUKUN NO.78', deliveryCycle: 'monthly' },
      { name: 'FRESH MART GRESIK', location: 'JL PANCENG NO.90', deliveryCycle: 'biweekly' },
      { name: 'MULTI MART', location: 'JL UJUNGPANGKAH NO.12', deliveryCycle: 'monthly' },
      { name: 'SMART MART', location: 'JL SANGKAPURA NO.34', deliveryCycle: 'weekly' },
      { name: 'MEGA MART', location: 'JL TAMBAK NO.56', deliveryCycle: 'monthly' },
      { name: 'STAR MART', location: 'JL WRINGINANOM NO.78', deliveryCycle: 'weekly' },
      { name: 'FAMILY MART', location: 'JL DRIYOREJO NO.90', deliveryCycle: 'monthly' },
      { name: 'QUICK MART', location: 'JL KEDAMEAN NO.12', deliveryCycle: 'monthly' },
      { name: 'DAILY MART', location: 'JL MENGARE NO.34', deliveryCycle: 'biweekly' },
      { name: 'HAPPY MART', location: 'JL SEMBAYAT NO.56', deliveryCycle: 'biweekly' },
      { name: 'MINI MARKET ABADI', location: 'JL CAMPUREJO NO.78', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET SEJAHTERA', location: 'JL SUKOMULYO NO.90', deliveryCycle: 'biweekly' },
      { name: 'MINI MARKET BERKAH', location: 'JL ROOMO NO.12', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET JAYA', location: 'JL SEGOROMADU NO.34', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET MAKMUR', location: 'JL INDRO NO.56', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET SENTOSA', location: 'JL RANDUAGUNG NO.78', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET BAROKAH', location: 'JL PETROKIMIA NO.90', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET ABADI', location: 'JL GKB NO.12', deliveryCycle: 'biweekly' },
      { name: 'MINI MARKET SEJATI', location: 'JL KOTA BARU NO.34', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET MAJU', location: 'JL VETERAN MADYA NO.56', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET JAYA', location: 'JL SUNAN GIRI NO.78', deliveryCycle: 'monthly' },
      {
        name: 'MINI MARKET BERKAH',
        location: 'JL KH WACHID HASYIM NO.90',
        deliveryCycle: 'weekly',
      },
      {
        name: 'MINI MARKET MAKMUR',
        location: 'JL MAYJEN SUNGKONO NO.12',
        deliveryCycle: 'biweekly',
      },
      {
        name: 'MINI MARKET SENTOSA',
        location: 'JL KAPTEN DULASIM NO.34',
        deliveryCycle: 'monthly',
      },
      {
        name: 'MINI MARKET BAROKAH',
        location: 'JL ARIF RAHMAN HAKIM NO.56',
        deliveryCycle: 'weekly',
      },
      { name: 'MINI MARKET ABADI', location: 'JL RAYA ROOMO NO.78', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET SEJATI', location: 'JL RAYA MANYAR NO.90', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET MAJU', location: 'JL RAYA BUNGAH NO.12', deliveryCycle: 'monthly' },
      { name: 'MINI MARKET JAYA', location: 'JL RAYA DUKUN NO.34', deliveryCycle: 'weekly' },
      { name: 'MINI MARKET BERKAH', location: 'JL RAYA MENGARE NO.56', deliveryCycle: 'biweekly' },
      { name: 'MINI MARKET MAKMUR', location: 'JL RAYA SEMBAYAT NO.78', deliveryCycle: 'monthly' },
      {
        name: 'MINI MARKET SENTOSA',
        location: 'JL RAYA CAMPUREJO NO.90',
        deliveryCycle: 'biweekly',
      },
      {
        name: 'MINI MARKET BAROKAH',
        location: 'JL RAYA SUKOMULYO NO.12',
        deliveryCycle: 'biweekly',
      },

      // Grosir/wholesale (10% = ~11 customers)
      { name: 'GROSIR MAKMUR JAYA', location: 'JL DR WAHIDIN NO.100', deliveryCycle: 'monthly' },
      { name: 'GROSIR SEJAHTERA', location: 'JL VETERAN NO.200', deliveryCycle: 'biweekly' },
      { name: 'GROSIR ABADI', location: 'JL GUBERNUR SURYO NO.150', deliveryCycle: 'monthly' },
      { name: 'GROSIR MAJU BERSAMA', location: 'JL USMAN SADAR NO.300', deliveryCycle: 'weekly' },
      { name: 'GROSIR BERKAH', location: 'JL SINDUJOYO NO.250', deliveryCycle: 'biweekly' },
      { name: 'GROSIR JAYA', location: 'JL JAKSA AGUNG SUPRAPTO NO.350', deliveryCycle: 'monthly' },
      { name: 'GROSIR MAKMUR', location: 'JL SAMANHUDI NO.400', deliveryCycle: 'biweekly' },
      { name: 'GROSIR SEJATI', location: 'JL KARTINI NO.450', deliveryCycle: 'monthly' },
      { name: 'GROSIR SENTOSA', location: 'JL PAHLAWAN NO.500', deliveryCycle: 'biweekly' },
      { name: 'GROSIR UTAMA', location: 'JL KH KHOLIL NO.550', deliveryCycle: 'monthly' },
      { name: 'GROSIR BAROKAH', location: 'JL PANGLIMA SUDIRMAN NO.600', deliveryCycle: 'weekly' },
    ],
  },
}

// Amount ranges for different transaction sizes
const amountRanges = {
  small: { min: 50000, max: 500000 },
  medium: { min: 500001, max: 2000000 },
  large: { min: 2000001, max: 15000000 },
}

const deliveryStatusConfig = {
  'DITERIMA - SEMUA': 0.7,
  'DITERIMA - SEBAGIAN': 0.15,
  'KIRIM ULANG': 0.05,
  'BATAL - TOKO TUTUP': 0.025,
  'BATAL - TIDAK ADA UANG': 0.025,
  'BATAL - SALAH ORDER': 0.025,
  'BATAL - TOKO TIDAK DAPAT DIAKSES': 0.025,
}

const paymentMethodConfig = {
  TUNAI: 0.6,
  KREDIT: 0.4,
}

const expenseCategoryConfig = {
  Fuel: {
    frequency: 'daily',
    range: { min: 300000, max: 1000000 },
  },
  Maintenance: {
    frequency: 'biweekly',
    range: { min: 800000, max: 2500000 },
  },
  'Vehicle License': {
    frequency: 'monthly',
    range: { min: 400000, max: 800000 },
  },
  Labour: {
    frequency: 'weekly',
    range: { min: 600000, max: 1000000 },
  },
  'Parking-Tol-Retribution': {
    frequency: 'daily',
    range: { min: 300000, max: 500000 },
  },
}

const vehicleStatusConfig = {
  fuelLevel: {
    startDay: { min: 80, max: 100 },
    midDay: { min: 40, max: 60 },
    endDay: { min: 20, max: 40 },
    refillTrigger: 30,
  },
  maintenanceSchedule: {
    interval: 14, // days
    duration: 1, // days
  },
}

const peakTimeConfig = {
  normalDeliveries: {
    min: 5,
    max: 10,
  },
  peakDeliveries: {
    min: 10,
    max: 15,
  },
  peakPeriods: {
    monthly: {
      // Last week of each month
      startDay: 23,
      endDay: 31,
    },
    december: {
      // Last two weeks of December
      startDay: 15,
      endDay: 31,
    },
  },
}

export {
  branchConfig,
  amountRanges,
  deliveryStatusConfig,
  paymentMethodConfig,
  expenseCategoryConfig,
  vehicleStatusConfig,
  peakTimeConfig,
}
