export const expensesMockData = [
  {
    id: 1,
    branch: "RDA SUMEDANG",
    date: "11/30/24",
    category: "Fuel",
    amount: 500000,
    vehicleNumber: "B9144SCN",
    driver: "SOEBANGKIT",
    description: "Fuel refill",
    status: "approved",
    receipt: "/uploads/receipts/exp001.jpg"
  },
  {
    id: 2,
    branch: "RDA SUMEDANG",
    date: "11/30/24",
    category: "Maintenance",
    amount: 1500000,
    vehicleNumber: "B9144SCN",
    driver: "SOEBANGKIT",
    description: "Monthly maintenance",
    status: "pending",
    receipt: "/uploads/receipts/exp002.jpg"
  },
    {
      "id": 1,
      "branch": "RDA GORONTALO",
      "date": "12/02/24",
      "category": "Fuel",
      "amount": 540738,
      "vehicleNumber": "B9144SCN",
      "driver": "SOEBANGKIT",
      "description": "Fuel related expense",
      "status": "approved",
      "receipt": "/uploads/receipts/exp001.jpg"
    },
    {
      "id": 2,
      "branch": "RDA MANADO",
      "date": "12/03/24",
      "category": "Maintenance",
      "amount": 1587000,
      "vehicleNumber": "B1234ABC",
      "driver": "JONO",
      "description": "Maintenance related expense",
      "status": "pending",
      "receipt": "/uploads/receipts/exp002.jpg"
    },
    {
      "id": 3,
      "branch": "RDA CIANJUR",
      "date": "12/04/24",
      "category": "Labour",
      "amount": 800000,
      "vehicleNumber": "B5678XYZ",
      "driver": "MARTIN",
      "description": "Labour related expense",
      "status": "approved",
      "receipt": "/uploads/receipts/exp003.jpg"
    },
    {
      "id": 4,
      "branch": "RDA SUMEDANG",
      "date": "12/05/24",
      "category": "Parking-Tol-Retribution",
      "amount": 400000,
      "vehicleNumber": "B9101LMN",
      "driver": "ALFIAN",
      "description": "Parking-Tol-Retribution related expense",
      "status": "rejected",
      "receipt": "/uploads/receipts/exp004.jpg"
    },
    {
      "id": 5,
      "branch": "RDA JEMBER",
      "date": "12/01/24",
      "category": "Vehicle License",
      "amount": 550000,
      "vehicleNumber": "B1122DEF",
      "driver": "RUDI",
      "description": "Vehicle License related expense",
      "status": "approved",
      "receipt": "/uploads/receipts/exp005.jpg"
    },
    {
      "id": 6,
      "branch": "RDA GRESIK",
      "date": "12/02/24",
      "category": "Fuel",
      "amount": 654321,
      "vehicleNumber": "B3344GHI",
      "driver": "ANDI",
      "description": "Fuel related expense",
      "status": "pending",
      "receipt": "/uploads/receipts/exp006.jpg"
    },
    {
      "id": 7,
      "branch": "RDA GORONTALO",
      "date": "12/03/24",
      "category": "Maintenance",
      "amount": 950000,
      "vehicleNumber": "B4466KLM",
      "driver": "RAHMAT",
      "description": "Maintenance related expense",
      "status": "approved",
      "receipt": "/uploads/receipts/exp007.jpg"
    },
    {
      "id": 8,
      "branch": "RDA MANADO",
      "date": "12/04/24",
      "category": "Labour",
      "amount": 670000,
      "vehicleNumber": "B9087XYZ",
      "driver": "ANTON",
      "description": "Labour related expense",
      "status": "rejected",
      "receipt": "/uploads/receipts/exp008.jpg"
    },
    {
      "id": 9,
      "branch": "RDA CIANJUR",
      "date": "12/05/24",
      "category": "Parking-Tol-Retribution",
      "amount": 320000,
      "vehicleNumber": "B1122DEF",
      "driver": "MARTIN",
      "description": "Parking-Tol-Retribution related expense",
      "status": "approved",
      "receipt": "/uploads/receipts/exp009.jpg"
    },
    {
      "id": 10,
      "branch": "RDA SUMEDANG",
      "date": "12/01/24",
      "category": "Vehicle License",
      "amount": 612000,
      "vehicleNumber": "B1177QWE",
      "driver": "ALFIAN",
      "description": "Vehicle License related expense",
      "status": "approved",
      "receipt": "/uploads/receipts/exp010.jpg"
    },
    {
      "id": 11,
      "branch": "RDA JEMBER",
      "date": "12/02/24",
      "category": "Fuel",
      "amount": 786543,
      "vehicleNumber": "B2334STU",
      "driver": "HADI",
      "description": "Fuel refill",
      "status": "pending",
      "receipt": "/uploads/receipts/exp011.jpg"
    },
    {
      "id": 12,
      "branch": "RDA GRESIK",
      "date": "12/03/24",
      "category": "Maintenance",
      "amount": 1234567,
      "vehicleNumber": "B3344GHI",
      "driver": "ANDI",
      "description": "Maintenance work",
      "status": "approved",
      "receipt": "/uploads/receipts/exp012.jpg"
    },
    {
      "id": 13,
      "branch": "RDA GORONTALO",
      "date": "12/04/24",
      "category": "Labour",
      "amount": 945000,
      "vehicleNumber": "B5566JKL",
      "driver": "SOEBANGKIT",
      "description": "Labour expense",
      "status": "rejected",
      "receipt": "/uploads/receipts/exp013.jpg"
    },
    {
      "id": 14,
      "branch": "RDA MANADO",
      "date": "12/05/24",
      "category": "Parking-Tol-Retribution",
      "amount": 389000,
      "vehicleNumber": "B2233ASD",
      "driver": "RUDI",
      "description": "Toll and parking charges",
      "status": "approved",
      "receipt": "/uploads/receipts/exp014.jpg"
    },
    {
      "id": 15,
      "branch": "RDA CIANJUR",
      "date": "12/01/24",
      "category": "Vehicle License",
      "amount": 700000,
      "vehicleNumber": "B5577KLM",
      "driver": "MARTIN",
      "description": "Vehicle registration",
      "status": "approved",
      "receipt": "/uploads/receipts/exp015.jpg"
    },
    {
      "id": 16,
      "branch": "RDA SUMEDANG",
      "date": "12/02/24",
      "category": "Fuel",
      "amount": 598000,
      "vehicleNumber": "B1122DEF",
      "driver": "RUDI",
      "description": "Fuel expense",
      "status": "pending",
      "receipt": "/uploads/receipts/exp016.jpg"
    },
    {
      "id": 17,
      "branch": "RDA JEMBER",
      "date": "12/03/24",
      "category": "Maintenance",
      "amount": 987654,
      "vehicleNumber": "B3344GHI",
      "driver": "ANDI",
      "description": "Vehicle maintenance",
      "status": "approved",
      "receipt": "/uploads/receipts/exp017.jpg"
    },
    {
      "id": 18,
      "branch": "RDA GRESIK",
      "date": "12/04/24",
      "category": "Labour",
      "amount": 623000,
      "vehicleNumber": "B5566JKL",
      "driver": "RAHMAT",
      "description": "Labour work",
      "status": "rejected",
      "receipt": "/uploads/receipts/exp018.jpg"
    },
    {
      "id": 19,
      "branch": "RDA GORONTALO",
      "date": "12/05/24",
      "category": "Parking-Tol-Retribution",
      "amount": 460000,
      "vehicleNumber": "B4455TYU",
      "driver": "SOEBANGKIT",
      "description": "Parking and toll charges",
      "status": "approved",
      "receipt": "/uploads/receipts/exp019.jpg"
    },
    {
      "id": 20,
      "branch": "RDA MANADO",
      "date": "12/01/24",
      "category": "Vehicle License",
      "amount": 640000,
      "vehicleNumber": "B1234ABC",
      "driver": "JONO",
      "description": "Vehicle license renewal",
      "status": "pending",
      "receipt": "/uploads/receipts/exp020.jpg"
    },
    {
      "id": 21,
      "branch": "RDA CIANJUR",
      "date": "12/02/24",
      "category": "Fuel",
      "amount": 545000,
      "vehicleNumber": "B7889DFG",
      "driver": "MARTIN",
      "description": "Fuel top-up",
      "status": "approved",
      "receipt": "/uploads/receipts/exp021.jpg"
    },
    {
      "id": 22,
      "branch": "RDA SUMEDANG",
      "date": "12/03/24",
      "category": "Maintenance",
      "amount": 2450000,
      "vehicleNumber": "B3344GHI",
      "driver": "ANDI",
      "description": "Routine maintenance",
      "status": "approved",
      "receipt": "/uploads/receipts/exp022.jpg"
    },
    {
      "id": 23,
      "branch": "RDA JEMBER",
      "date": "12/04/24",
      "category": "Labour",
      "amount": 720000,
      "vehicleNumber": "B1122DEF",
      "driver": "RUDI",
      "description": "Labour expense",
      "status": "pending",
      "receipt": "/uploads/receipts/exp023.jpg"
    },
    {
      "id": 24,
      "branch": "RDA GRESIK",
      "date": "12/05/24",
      "category": "Parking-Tol-Retribution",
      "amount": 350000,
      "vehicleNumber": "B3344GHI",
      "driver": "RAHMAT",
      "description": "Toll charges",
      "status": "approved",
      "receipt": "/uploads/receipts/exp024.jpg"
    },
    {
      "id": 25,
      "branch": "RDA GORONTALO",
      "date": "12/01/24",
      "category": "Vehicle License",
      "amount": 503000,
      "vehicleNumber": "B9101LMN",
      "driver": "ALFIAN",
      "description": "Vehicle registration",
      "status": "approved",
      "receipt": "/uploads/receipts/exp025.jpg"
    },
    {
    "id": 26,
    "branch": "RDA CIANJUR",
    "date": "12/02/24",
    "category": "Fuel",
    "amount": 450000,
    "vehicleNumber": "B1122XCV",
    "driver": "JOHAN",
    "description": "Fuel refilling",
    "status": "approved",
    "receipt": "/uploads/receipts/exp026.jpg"
  },
  {
    "id": 27,
    "branch": "RDA SUMEDANG",
    "date": "12/03/24",
    "category": "Maintenance",
    "amount": 1100000,
    "vehicleNumber": "B4455ASD",
    "driver": "BUDI",
    "description": "Maintenance service",
    "status": "pending",
    "receipt": "/uploads/receipts/exp027.jpg"
  },
  {
    "id": 28,
    "branch": "RDA JEMBER",
    "date": "12/04/24",
    "category": "Labour",
    "amount": 800000,
    "vehicleNumber": "B7788DFG",
    "driver": "RAHMAT",
    "description": "Labour expense",
    "status": "approved",
    "receipt": "/uploads/receipts/exp028.jpg"
  },
  {
    "id": 29,
    "branch": "RDA GRESIK",
    "date": "12/05/24",
    "category": "Parking-Tol-Retribution",
    "amount": 390000,
    "vehicleNumber": "B2233JKL",
    "driver": "ANDI",
    "description": "Toll fee",
    "status": "rejected",
    "receipt": "/uploads/receipts/exp029.jpg"
  },
  {
    "id": 30,
    "branch": "RDA GORONTALO",
    "date": "12/01/24",
    "category": "Vehicle License",
    "amount": 750000,
    "vehicleNumber": "B4455MNO",
    "driver": "SOEBANGKIT",
    "description": "License fee",
    "status": "approved",
    "receipt": "/uploads/receipts/exp030.jpg"
  },
  {
    "id": 31,
    "branch": "RDA MANADO",
    "date": "12/02/24",
    "category": "Fuel",
    "amount": 570000,
    "vehicleNumber": "B7788VBN",
    "driver": "JONO",
    "description": "Fuel expenses",
    "status": "approved",
    "receipt": "/uploads/receipts/exp031.jpg"
  },
  {
    "id": 32,
    "branch": "RDA CIANJUR",
    "date": "12/03/24",
    "category": "Maintenance",
    "amount": 1290000,
    "vehicleNumber": "B9988JKL",
    "driver": "MARTIN",
    "description": "Repair costs",
    "status": "pending",
    "receipt": "/uploads/receipts/exp032.jpg"
  },
  {
    "id": 33,
    "branch": "RDA SUMEDANG",
    "date": "12/04/24",
    "category": "Labour",
    "amount": 950000,
    "vehicleNumber": "B1122DEF",
    "driver": "ALFIAN",
    "description": "Labour charge",
    "status": "approved",
    "receipt": "/uploads/receipts/exp033.jpg"
  },
  {
    "id": 34,
    "branch": "RDA JEMBER",
    "date": "12/05/24",
    "category": "Parking-Tol-Retribution",
    "amount": 540000,
    "vehicleNumber": "B3344KLM",
    "driver": "RUDI",
    "description": "Parking and toll charges",
    "status": "rejected",
    "receipt": "/uploads/receipts/exp034.jpg"
  },
  {
    "id": 35,
    "branch": "RDA GRESIK",
    "date": "12/01/24",
    "category": "Vehicle License",
    "amount": 670000,
    "vehicleNumber": "B5566ASD",
    "driver": "RAHMAT",
    "description": "License renewal",
    "status": "approved",
    "receipt": "/uploads/receipts/exp035.jpg"
  },
  {
    "id": 36,
    "branch": "RDA GORONTALO",
    "date": "12/02/24",
    "category": "Fuel",
    "amount": 850000,
    "vehicleNumber": "B2233POI",
    "driver": "SOEBANGKIT",
    "description": "Fuel purchase",
    "status": "approved",
    "receipt": "/uploads/receipts/exp036.jpg"
  },
  {
    "id": 37,
    "branch": "RDA MANADO",
    "date": "12/03/24",
    "category": "Maintenance",
    "amount": 1325000,
    "vehicleNumber": "B3344FGE",
    "driver": "ALFIAN",
    "description": "Maintenance work",
    "status": "pending",
    "receipt": "/uploads/receipts/exp037.jpg"
  },
  {
    "id": 38,
    "branch": "RDA CIANJUR",
    "date": "12/04/24",
    "category": "Labour",
    "amount": 600000,
    "vehicleNumber": "B7788TGH",
    "driver": "MARTIN",
    "description": "Workman charges",
    "status": "approved",
    "receipt": "/uploads/receipts/exp038.jpg"
  },
  {
    "id": 39,
    "branch": "RDA SUMEDANG",
    "date": "12/05/24",
    "category": "Parking-Tol-Retribution",
    "amount": 400000,
    "vehicleNumber": "B4455XYZ",
    "driver": "ANDI",
    "description": "Toll charge",
    "status": "rejected",
    "receipt": "/uploads/receipts/exp039.jpg"
  },
  {
    "id": 40,
    "branch": "RDA JEMBER",
    "date": "12/01/24",
    "category": "Vehicle License",
    "amount": 530000,
    "vehicleNumber": "B7788MNB",
    "driver": "RAHMAT",
    "description": "Registration fee",
    "status": "approved",
    "receipt": "/uploads/receipts/exp040.jpg"
  },
  {
    "id": 41,
    "branch": "RDA GRESIK",
    "date": "12/02/24",
    "category": "Fuel",
    "amount": 725000,
    "vehicleNumber": "B3321DJK",
    "driver": "ANDI",
    "description": "Fuel replenishment",
    "status": "approved",
    "receipt": "/uploads/receipts/exp041.jpg"
  },
  {
    "id": 42,
    "branch": "RDA GORONTALO",
    "date": "12/03/24",
    "category": "Maintenance",
    "amount": 980000,
    "vehicleNumber": "B4455JKL",
    "driver": "SOEBANGKIT",
    "description": "Vehicle maintenance",
    "status": "pending",
    "receipt": "/uploads/receipts/exp042.jpg"
  },
  {
    "id": 43,
    "branch": "RDA MANADO",
    "date": "12/04/24",
    "category": "Labour",
    "amount": 730000,
    "vehicleNumber": "B2233ASD",
    "driver": "JONO",
    "description": "Labour charges",
    "status": "rejected",
    "receipt": "/uploads/receipts/exp043.jpg"
  },
  {
    "id": 44,
    "branch": "RDA CIANJUR",
    "date": "12/05/24",
    "category": "Parking-Tol-Retribution",
    "amount": 370000,
    "vehicleNumber": "B7788JKL",
    "driver": "MARTIN",
    "description": "Toll fee",
    "status": "approved",
    "receipt": "/uploads/receipts/exp044.jpg"
  },
  {
    "id": 45,
    "branch": "RDA SUMEDANG",
    "date": "12/01/24",
    "category": "Vehicle License",
    "amount": 480000,
    "vehicleNumber": "B3344VBN",
    "driver": "ALFIAN",
    "description": "License payment",
    "status": "approved",
    "receipt": "/uploads/receipts/exp045.jpg"
  },
  {
    "id": 46,
    "branch": "RDA JEMBER",
    "date": "12/02/24",
    "category": "Fuel",
    "amount": 395000,
    "vehicleNumber": "B7788NSD",
    "driver": "RUDI",
    "description": "Fuel expense",
    "status": "approved",
    "receipt": "/uploads/receipts/exp046.jpg"
  },
  {
    "id": 47,
    "branch": "RDA GRESIK",
    "date": "12/03/24",
    "category": "Maintenance",
    "amount": 1180000,
    "vehicleNumber": "B2333FTY",
    "driver": "RAHMAT",
    "description": "Maintenance work",
    "status": "approved",
    "receipt": "/uploads/receipts/exp047.jpg"
  }
]
